set_property MARK_DEBUG true [get_nets design_1_wrapper_i/design_1_i_n_2]
set_property MARK_DEBUG true [get_nets design_1_wrapper_i/design_1_i_n_16]
set_property MARK_DEBUG false [get_nets Hsync_OBUF]
set_property MARK_DEBUG false [get_nets Vsync_OBUF]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/v_axi4s_vid_out_0/vid_data[22]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/v_axi4s_vid_out_0/vid_data[23]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/xlslice_0/Din[22]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/xlslice_0/Din[20]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/vgaBlue[0]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/v_axi4s_vid_out_0_vid_data[22]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/vgaBlue[3]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/xlslice_0/Din[23]}]
set_property MARK_DEBUG false [get_nets {vgaBlue_OBUF[3]}]
set_property MARK_DEBUG false [get_nets {vgaBlue_OBUF[1]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/v_axi4s_vid_out_0_vid_data[23]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/v_axi4s_vid_out_0/inst/vid_data[21]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/v_axi4s_vid_out_0/vid_data[20]}]
set_property MARK_DEBUG false [get_nets {vgaBlue_OBUF[0]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/v_axi4s_vid_out_0/inst/vid_data[20]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/v_axi4s_vid_out_0/inst/vid_data[22]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/v_axi4s_vid_out_0_vid_data[21]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/v_axi4s_vid_out_0/inst/FORMATTER_INST/vid_data[22]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/v_axi4s_vid_out_0/inst/FORMATTER_INST/vid_data[21]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/v_axi4s_vid_out_0/inst/FORMATTER_INST/vid_data[23]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/v_axi4s_vid_out_0/vid_data[21]}]
set_property MARK_DEBUG false [get_nets {vgaBlue_OBUF[2]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/v_axi4s_vid_out_0_vid_data[20]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/vgaBlue[2]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/vgaBlue[1]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/v_axi4s_vid_out_0/inst/vid_data[23]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/v_axi4s_vid_out_0/inst/FORMATTER_INST/vid_data[20]}]
set_property MARK_DEBUG false [get_nets {design_1_wrapper_i/design_1_i/xlslice_0/Din[21]}]
set_property MARK_DEBUG false [get_nets {vgaGreen_OBUF[1]}]
set_property MARK_DEBUG false [get_nets {vgaGreen_OBUF[0]}]
set_property MARK_DEBUG false [get_nets {vgaGreen_OBUF[3]}]
set_property MARK_DEBUG false [get_nets {vgaGreen_OBUF[2]}]
set_property MARK_DEBUG false [get_nets {vgaRed_OBUF[2]}]
set_property MARK_DEBUG false [get_nets {vgaRed_OBUF[0]}]
set_property MARK_DEBUG false [get_nets {vgaRed_OBUF[1]}]
set_property MARK_DEBUG false [get_nets {vgaRed_OBUF[3]}]
set_property MARK_DEBUG true [get_nets design_1_wrapper_i/Hsync]
set_property MARK_DEBUG true [get_nets design_1_wrapper_i/Vsync]
set_property MARK_DEBUG true [get_nets {design_1_wrapper_i/vgaBlue[2]}]
set_property MARK_DEBUG true [get_nets {design_1_wrapper_i/vgaBlue[3]}]
set_property MARK_DEBUG true [get_nets {design_1_wrapper_i/vgaBlue[1]}]
set_property MARK_DEBUG true [get_nets {design_1_wrapper_i/vgaBlue[0]}]
set_property MARK_DEBUG true [get_nets {design_1_wrapper_i/vgaGreen[3]}]
set_property MARK_DEBUG true [get_nets {design_1_wrapper_i/vgaGreen[2]}]
set_property MARK_DEBUG true [get_nets {design_1_wrapper_i/vgaGreen[0]}]
set_property MARK_DEBUG true [get_nets {design_1_wrapper_i/vgaGreen[1]}]
set_property MARK_DEBUG true [get_nets {design_1_wrapper_i/vgaRed[3]}]
set_property MARK_DEBUG true [get_nets {design_1_wrapper_i/vgaRed[1]}]
set_property MARK_DEBUG true [get_nets {design_1_wrapper_i/vgaRed[2]}]
set_property MARK_DEBUG true [get_nets {design_1_wrapper_i/vgaRed[0]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_wrapper_i/design_1_i/clk_wiz_1/inst/clk_video]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_wrapper_i/vgaBlue[0]} {design_1_wrapper_i/vgaBlue[1]} {design_1_wrapper_i/vgaBlue[2]} {design_1_wrapper_i/vgaBlue[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_wrapper_i/vgaGreen[0]} {design_1_wrapper_i/vgaGreen[1]} {design_1_wrapper_i/vgaGreen[2]} {design_1_wrapper_i/vgaGreen[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_wrapper_i/vgaRed[0]} {design_1_wrapper_i/vgaRed[1]} {design_1_wrapper_i/vgaRed[2]} {design_1_wrapper_i/vgaRed[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list design_1_wrapper_i/design_1_i_n_2]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list design_1_wrapper_i/design_1_i_n_16]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list design_1_wrapper_i/Hsync]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list design_1_wrapper_i/Vsync]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_video]
