webtalk_init -webtalk_dir /home/trevor/dev/myelect/vivado_video/XVES_0013/proj_1/proj_1.sim/sim_1/behav/xsim/xsim.dir/tb_AXI4S_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan 24 20:20:39 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a215616a-f984-4752-a61c-60b340cf6dbd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9629dcf784ee4642b5e3cfdfa195eb72" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "17" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790T CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2693.667 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "15001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "99.83_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "145284_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2172766706 -regid "" -xml /home/trevor/dev/myelect/vivado_video/XVES_0013/proj_1/proj_1.sim/sim_1/behav/xsim/xsim.dir/tb_AXI4S_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/trevor/dev/myelect/vivado_video/XVES_0013/proj_1/proj_1.sim/sim_1/behav/xsim/xsim.dir/tb_AXI4S_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/trevor/dev/myelect/vivado_video/XVES_0013/proj_1/proj_1.sim/sim_1/behav/xsim/xsim.dir/tb_AXI4S_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
