// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mandelbrot,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200tfbg676-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=83.138750,HLS_SYN_LAT=267,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=130,HLS_SYN_FF=2110,HLS_SYN_LUT=7295}" *)

module mandelbrot (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        re,
        im,
        outp,
        outp_ap_vld
);

parameter    ap_ST_fsm_state1 = 19'd1;
parameter    ap_ST_fsm_state2 = 19'd2;
parameter    ap_ST_fsm_state3 = 19'd4;
parameter    ap_ST_fsm_state4 = 19'd8;
parameter    ap_ST_fsm_state5 = 19'd16;
parameter    ap_ST_fsm_pp0_stage0 = 19'd32;
parameter    ap_ST_fsm_pp0_stage1 = 19'd64;
parameter    ap_ST_fsm_pp0_stage2 = 19'd128;
parameter    ap_ST_fsm_pp0_stage3 = 19'd256;
parameter    ap_ST_fsm_pp0_stage4 = 19'd512;
parameter    ap_ST_fsm_pp0_stage5 = 19'd1024;
parameter    ap_ST_fsm_pp0_stage6 = 19'd2048;
parameter    ap_ST_fsm_pp0_stage7 = 19'd4096;
parameter    ap_ST_fsm_pp0_stage8 = 19'd8192;
parameter    ap_ST_fsm_pp0_stage9 = 19'd16384;
parameter    ap_ST_fsm_pp0_stage10 = 19'd32768;
parameter    ap_ST_fsm_pp0_stage11 = 19'd65536;
parameter    ap_ST_fsm_pp0_stage12 = 19'd131072;
parameter    ap_ST_fsm_state22 = 19'd262144;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] re;
input  [31:0] im;
output  [15:0] outp;
output   outp_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg outp_ap_vld;

(* fsm_encoding = "none" *) reg   [18:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] p_Val2_36_12_reg_184;
reg   [31:0] p_Val2_39_12_reg_194;
reg   [7:0] i_reg_204;
reg   [15:0] mandelbrot_float_fl_reg_216;
wire   [0:0] isneg_fu_239_p3;
reg   [0:0] isneg_reg_3021;
wire   [53:0] man_V_4_fu_283_p3;
reg   [53:0] man_V_4_reg_3027;
wire   [0:0] tmp_7_fu_291_p2;
reg   [0:0] tmp_7_reg_3034;
wire   [11:0] F2_fu_297_p2;
reg   [11:0] F2_reg_3038;
wire   [0:0] tmp_9_fu_303_p2;
reg   [0:0] tmp_9_reg_3046;
wire   [11:0] tmp_s_fu_309_p2;
reg   [11:0] tmp_s_reg_3052;
wire   [11:0] tmp_1_fu_315_p2;
reg   [11:0] tmp_1_reg_3058;
wire  signed [31:0] sh_amt_cast_fu_326_p1;
reg  signed [31:0] sh_amt_cast_reg_3063;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_3_fu_330_p2;
reg   [0:0] tmp_3_reg_3068;
wire   [31:0] tmp_24_fu_335_p1;
reg   [31:0] tmp_24_reg_3075;
wire   [0:0] icmp_fu_354_p2;
reg   [0:0] icmp_reg_3082;
wire   [31:0] p_Val2_5_fu_420_p2;
reg   [31:0] p_Val2_5_reg_3088;
wire   [0:0] sel_tmp6_fu_426_p2;
reg   [0:0] sel_tmp6_reg_3094;
wire   [0:0] tmp_15_fu_431_p2;
reg   [0:0] tmp_15_reg_3099;
wire   [0:0] isneg_1_fu_499_p3;
reg   [0:0] isneg_1_reg_3103;
wire    ap_CS_fsm_state3;
wire   [53:0] man_V_11_fu_543_p3;
reg   [53:0] man_V_11_reg_3109;
wire   [0:0] tmp_18_fu_551_p2;
reg   [0:0] tmp_18_reg_3116;
wire   [11:0] F2_1_fu_557_p2;
reg   [11:0] F2_1_reg_3120;
wire   [0:0] tmp_19_fu_563_p2;
reg   [0:0] tmp_19_reg_3128;
wire   [11:0] tmp_20_fu_569_p2;
reg   [11:0] tmp_20_reg_3134;
wire   [11:0] tmp_21_fu_575_p2;
reg   [11:0] tmp_21_reg_3140;
wire  signed [31:0] sh_amt_1_cast_fu_586_p1;
reg  signed [31:0] sh_amt_1_cast_reg_3145;
wire    ap_CS_fsm_state4;
wire   [0:0] tmp_22_fu_590_p2;
reg   [0:0] tmp_22_reg_3150;
wire   [31:0] tmp_47_fu_595_p1;
reg   [31:0] tmp_47_reg_3157;
wire   [0:0] icmp5_fu_614_p2;
reg   [0:0] icmp5_reg_3164;
wire   [31:0] p_Val2_8_fu_680_p2;
reg   [31:0] p_Val2_8_reg_3170;
wire   [0:0] sel_tmp10_fu_686_p2;
reg   [0:0] sel_tmp10_reg_3176;
wire   [0:0] tmp_33_fu_691_p2;
reg   [0:0] tmp_33_reg_3181;
wire  signed [66:0] tmp_71_cast_cast_fu_759_p1;
reg  signed [66:0] tmp_71_cast_cast_reg_3185;
wire    ap_CS_fsm_state5;
reg   [31:0] p_Val2_1_reg_3202;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state6_pp0_stage0_iter0;
wire    ap_block_state19_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] tmp_51_reg_3207;
reg   [31:0] p_Val2_9_reg_3212;
reg   [0:0] tmp_52_reg_3217;
wire   [64:0] p_Val2_11_fu_835_p2;
reg   [64:0] p_Val2_11_reg_3222;
reg   [0:0] tmp_53_reg_3227;
wire   [0:0] tmp_40_fu_879_p2;
reg   [0:0] tmp_40_reg_3232;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state7_pp0_stage1_iter0;
wire    ap_block_state20_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_11001;
wire   [31:0] p_Val2_14_fu_906_p2;
reg   [31:0] p_Val2_14_reg_3237;
wire   [31:0] p_Val2_16_fu_918_p2;
reg   [31:0] p_Val2_16_reg_3243;
reg   [31:0] p_Val2_27_1_reg_3249;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state8_pp0_stage2_iter0;
wire    ap_block_state21_pp0_stage2_iter1;
wire    ap_block_pp0_stage2_11001;
reg   [0:0] tmp_54_reg_3254;
reg   [31:0] p_Val2_30_1_reg_3259;
reg   [0:0] tmp_55_reg_3264;
wire   [64:0] p_Val2_32_1_fu_992_p2;
reg   [64:0] p_Val2_32_1_reg_3269;
reg   [0:0] tmp_56_reg_3274;
wire   [0:0] tmp_94_1_fu_1036_p2;
reg   [0:0] tmp_94_1_reg_3279;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state9_pp0_stage3_iter0;
wire    ap_block_pp0_stage3_11001;
wire   [31:0] p_Val2_36_1_fu_1063_p2;
reg   [31:0] p_Val2_36_1_reg_3284;
wire   [31:0] p_Val2_39_1_fu_1075_p2;
reg   [31:0] p_Val2_39_1_reg_3290;
reg   [31:0] p_Val2_27_2_reg_3296;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state10_pp0_stage4_iter0;
wire    ap_block_pp0_stage4_11001;
reg   [0:0] tmp_57_reg_3301;
reg   [31:0] p_Val2_30_2_reg_3306;
reg   [0:0] tmp_58_reg_3311;
wire   [64:0] p_Val2_32_2_fu_1149_p2;
reg   [64:0] p_Val2_32_2_reg_3316;
reg   [0:0] tmp_59_reg_3321;
wire   [0:0] tmp_94_2_fu_1193_p2;
reg   [0:0] tmp_94_2_reg_3326;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state11_pp0_stage5_iter0;
wire    ap_block_pp0_stage5_11001;
wire   [31:0] p_Val2_36_2_fu_1220_p2;
reg   [31:0] p_Val2_36_2_reg_3331;
wire   [31:0] p_Val2_39_2_fu_1232_p2;
reg   [31:0] p_Val2_39_2_reg_3337;
reg   [31:0] p_Val2_27_3_reg_3343;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state12_pp0_stage6_iter0;
wire    ap_block_pp0_stage6_11001;
reg   [0:0] tmp_60_reg_3348;
reg   [31:0] p_Val2_30_3_reg_3353;
reg   [0:0] tmp_61_reg_3358;
wire   [64:0] p_Val2_32_3_fu_1306_p2;
reg   [64:0] p_Val2_32_3_reg_3363;
reg   [0:0] tmp_62_reg_3368;
wire   [0:0] tmp_94_3_fu_1350_p2;
reg   [0:0] tmp_94_3_reg_3373;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state13_pp0_stage7_iter0;
wire    ap_block_pp0_stage7_11001;
wire   [31:0] p_Val2_36_3_fu_1377_p2;
reg   [31:0] p_Val2_36_3_reg_3378;
wire   [31:0] p_Val2_39_3_fu_1389_p2;
reg   [31:0] p_Val2_39_3_reg_3384;
reg   [31:0] p_Val2_27_4_reg_3390;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_state14_pp0_stage8_iter0;
wire    ap_block_pp0_stage8_11001;
reg   [0:0] tmp_63_reg_3395;
reg   [31:0] p_Val2_30_4_reg_3400;
reg   [0:0] tmp_64_reg_3405;
wire   [64:0] p_Val2_32_4_fu_1463_p2;
reg   [64:0] p_Val2_32_4_reg_3410;
reg   [0:0] tmp_65_reg_3415;
wire   [0:0] tmp_94_4_fu_1507_p2;
reg   [0:0] tmp_94_4_reg_3420;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_state15_pp0_stage9_iter0;
wire    ap_block_pp0_stage9_11001;
wire   [31:0] p_Val2_36_4_fu_1534_p2;
reg   [31:0] p_Val2_36_4_reg_3425;
wire   [31:0] p_Val2_39_4_fu_1546_p2;
reg   [31:0] p_Val2_39_4_reg_3431;
reg   [31:0] p_Val2_27_5_reg_3437;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_state16_pp0_stage10_iter0;
wire    ap_block_pp0_stage10_11001;
reg   [0:0] tmp_66_reg_3442;
reg   [31:0] p_Val2_30_5_reg_3447;
reg   [0:0] tmp_67_reg_3452;
wire   [64:0] p_Val2_32_5_fu_1620_p2;
reg   [64:0] p_Val2_32_5_reg_3457;
reg   [0:0] tmp_68_reg_3462;
wire   [0:0] tmp_94_5_fu_1664_p2;
reg   [0:0] tmp_94_5_reg_3467;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_state17_pp0_stage11_iter0;
wire    ap_block_pp0_stage11_11001;
wire   [31:0] p_Val2_36_5_fu_1691_p2;
reg   [31:0] p_Val2_36_5_reg_3472;
wire   [31:0] p_Val2_39_5_fu_1703_p2;
reg   [31:0] p_Val2_39_5_reg_3478;
reg   [31:0] p_Val2_27_6_reg_3484;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_state18_pp0_stage12_iter0;
wire    ap_block_pp0_stage12_11001;
reg   [0:0] tmp_69_reg_3489;
reg   [31:0] p_Val2_30_6_reg_3494;
reg   [0:0] tmp_70_reg_3499;
wire   [64:0] p_Val2_32_6_fu_1777_p2;
reg   [64:0] p_Val2_32_6_reg_3504;
reg   [0:0] tmp_71_reg_3509;
wire   [0:0] exitcond_9_fu_1791_p2;
reg   [0:0] exitcond_9_reg_3514;
wire   [15:0] tmp1_fu_2159_p2;
reg   [15:0] tmp1_reg_3518;
wire   [1:0] tmp3_fu_2171_p2;
reg   [1:0] tmp3_reg_3523;
wire   [1:0] tmp7_fu_2183_p2;
reg   [1:0] tmp7_reg_3528;
wire   [0:0] tmp_94_9_fu_2350_p2;
reg   [0:0] tmp_94_9_reg_3533;
wire   [0:0] tmp_94_s_fu_2517_p2;
reg   [0:0] tmp_94_s_reg_3538;
wire   [0:0] tmp_94_10_fu_2684_p2;
reg   [0:0] tmp_94_10_reg_3543;
wire   [0:0] tmp_94_11_fu_2851_p2;
reg   [0:0] tmp_94_11_reg_3548;
wire   [31:0] p_Val2_36_11_fu_2910_p2;
reg    ap_enable_reg_pp0_iter1;
wire   [31:0] p_Val2_39_11_fu_2922_p2;
wire   [15:0] tmp_96_8_fu_2965_p2;
reg   [15:0] tmp_96_8_reg_3563;
wire   [15:0] tmp_96_1_fu_3004_p2;
wire   [7:0] i_1_s_fu_3010_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage12_subdone;
wire    ap_block_pp0_stage1_subdone;
wire   [31:0] p_s_fu_467_p3;
reg   [31:0] z0_re_V_load_reg_129;
wire   [31:0] tmp_4_mux_fu_477_p3;
reg   [31:0] z_re_V_load_reg_143;
wire   [31:0] tmp_15_s_fu_483_p3;
wire   [31:0] p_2_fu_727_p3;
reg   [31:0] ap_phi_mux_z0_im_V_load_phi_fu_161_p6;
reg   [31:0] z0_im_V_load_reg_157;
wire   [31:0] tmp_43_mux_fu_737_p3;
reg   [31:0] ap_phi_mux_p_3_phi_fu_174_p6;
reg   [31:0] p_3_reg_170;
wire   [31:0] tmp_50_s_fu_743_p3;
reg   [31:0] ap_phi_mux_p_Val2_36_12_phi_fu_187_p4;
wire    ap_block_pp0_stage0;
reg   [31:0] ap_phi_mux_p_Val2_39_12_phi_fu_197_p4;
wire    ap_CS_fsm_state22;
reg   [31:0] grp_fu_227_p0;
wire   [63:0] grp_fu_227_p1;
wire   [63:0] p_Val2_s_fu_231_p1;
wire   [10:0] exp_tmp_V_fu_247_p4;
wire   [51:0] tmp_11_fu_261_p1;
wire   [52:0] tmp_fu_265_p3;
wire   [53:0] man_V_fu_273_p1;
wire   [53:0] man_V_1_fu_277_p2;
wire   [62:0] tmp_4_fu_235_p1;
wire   [11:0] tmp_2_fu_257_p1;
wire   [11:0] sh_amt_fu_321_p3;
wire   [6:0] tmp_26_fu_344_p4;
wire   [53:0] tmp_8_fu_360_p1;
wire   [53:0] tmp_6_fu_364_p2;
wire   [0:0] tmp_5_fu_338_p2;
wire   [31:0] tmp_29_fu_369_p1;
wire   [31:0] p_Val2_0_i_i_i1_fu_373_p3;
wire   [11:0] tmp_13_fu_393_p2;
wire  signed [31:0] tmp_17_cast_fu_398_p1;
wire   [0:0] tmp_12_fu_388_p2;
wire   [0:0] tmp_42_fu_402_p3;
wire   [0:0] qb_fu_409_p3;
wire   [31:0] tmp_14_fu_416_p1;
wire   [31:0] p_Val2_4_fu_380_p3;
wire   [0:0] sel_tmp1_fu_446_p2;
wire   [0:0] sel_tmp2_fu_451_p2;
wire   [31:0] sel_tmp_fu_440_p3;
wire   [0:0] sel_tmp7_fu_463_p2;
wire   [31:0] tmp_10_fu_436_p2;
wire   [31:0] sel_tmp3_fu_456_p3;
wire   [63:0] p_Val2_21_fu_491_p1;
wire   [10:0] exp_tmp_V_1_fu_507_p4;
wire   [51:0] tmp_46_fu_521_p1;
wire   [52:0] tmp_17_fu_525_p3;
wire   [53:0] man_V_10_fu_533_p1;
wire   [53:0] man_V_6_fu_537_p2;
wire   [62:0] tmp_44_fu_495_p1;
wire   [11:0] tmp_16_fu_517_p1;
wire   [11:0] sh_amt_1_fu_581_p3;
wire   [6:0] tmp_48_fu_604_p4;
wire   [53:0] tmp_25_fu_620_p1;
wire   [53:0] tmp_27_fu_624_p2;
wire   [0:0] tmp_23_fu_598_p2;
wire   [31:0] tmp_49_fu_629_p1;
wire   [31:0] p_Val2_0_i_i_i5_fu_633_p3;
wire   [11:0] tmp_31_fu_653_p2;
wire  signed [31:0] tmp_52_cast_fu_658_p1;
wire   [0:0] tmp_30_fu_648_p2;
wire   [0:0] tmp_50_fu_662_p3;
wire   [0:0] qb_1_fu_669_p3;
wire   [31:0] tmp_32_fu_676_p1;
wire   [31:0] p_Val2_7_fu_640_p3;
wire   [0:0] sel_tmp5_fu_706_p2;
wire   [0:0] sel_tmp8_fu_711_p2;
wire   [31:0] sel_tmp4_fu_700_p3;
wire   [0:0] sel_tmp11_fu_723_p2;
wire   [31:0] tmp_28_fu_696_p2;
wire   [31:0] sel_tmp9_fu_716_p3;
wire   [59:0] tmp_34_fu_751_p3;
wire  signed [31:0] p_Val2_s_8_fu_767_p0;
wire  signed [63:0] OP1_V_3_fu_763_p1;
wire  signed [31:0] p_Val2_s_8_fu_767_p1;
wire   [63:0] p_Val2_s_8_fu_767_p2;
wire  signed [31:0] p_Val2_3_fu_795_p0;
wire  signed [63:0] OP1_V_4_fu_791_p1;
wire  signed [31:0] p_Val2_3_fu_795_p1;
wire   [63:0] p_Val2_3_fu_795_p2;
wire   [32:0] r_V_1_fu_819_p3;
wire  signed [31:0] p_Val2_11_fu_835_p0;
wire  signed [32:0] p_Val2_11_fu_835_p1;
wire    ap_block_pp0_stage1;
wire   [31:0] tmp_35_fu_849_p1;
wire   [31:0] tmp_37_fu_857_p1;
wire   [31:0] p_Val2_2_fu_852_p2;
wire   [31:0] p_Val2_10_fu_860_p2;
wire  signed [32:0] tmp_39_fu_869_p1;
wire  signed [32:0] tmp_38_fu_865_p1;
wire   [32:0] r_V_fu_873_p2;
wire   [66:0] tmp_42_cast_fu_885_p1;
wire   [66:0] p_Val2_12_fu_888_p2;
wire   [31:0] tmp_41_fu_903_p1;
wire   [31:0] p_Val2_13_fu_893_p4;
wire   [31:0] p_Val2_15_fu_912_p2;
wire    ap_block_pp0_stage2;
wire  signed [31:0] p_Val2_26_1_fu_927_p0;
wire  signed [63:0] OP1_V_3_1_fu_924_p1;
wire  signed [31:0] p_Val2_26_1_fu_927_p1;
wire   [63:0] p_Val2_26_1_fu_927_p2;
wire  signed [31:0] p_Val2_29_1_fu_954_p0;
wire  signed [63:0] OP1_V_4_1_fu_951_p1;
wire  signed [31:0] p_Val2_29_1_fu_954_p1;
wire   [63:0] p_Val2_29_1_fu_954_p2;
wire   [32:0] r_V_1_1_fu_978_p3;
wire  signed [31:0] p_Val2_32_1_fu_992_p0;
wire  signed [32:0] p_Val2_32_1_fu_992_p1;
wire    ap_block_pp0_stage3;
wire   [31:0] tmp_85_1_fu_1006_p1;
wire   [31:0] tmp_89_1_fu_1014_p1;
wire   [31:0] p_Val2_28_1_fu_1009_p2;
wire   [31:0] p_Val2_31_1_fu_1017_p2;
wire  signed [32:0] tmp_92_1_fu_1022_p1;
wire  signed [32:0] tmp_93_1_fu_1026_p1;
wire   [32:0] r_V_s_fu_1030_p2;
wire   [66:0] tmp_973_1_cast_fu_1042_p1;
wire   [66:0] p_Val2_34_1_fu_1045_p2;
wire   [31:0] tmp_101_1_fu_1060_p1;
wire   [31:0] p_Val2_35_1_fu_1050_p4;
wire   [31:0] p_Val2_37_1_fu_1069_p2;
wire    ap_block_pp0_stage4;
wire  signed [31:0] p_Val2_26_2_fu_1084_p0;
wire  signed [63:0] OP1_V_3_2_fu_1081_p1;
wire  signed [31:0] p_Val2_26_2_fu_1084_p1;
wire   [63:0] p_Val2_26_2_fu_1084_p2;
wire  signed [31:0] p_Val2_29_2_fu_1111_p0;
wire  signed [63:0] OP1_V_4_2_fu_1108_p1;
wire  signed [31:0] p_Val2_29_2_fu_1111_p1;
wire   [63:0] p_Val2_29_2_fu_1111_p2;
wire   [32:0] r_V_1_2_fu_1135_p3;
wire  signed [31:0] p_Val2_32_2_fu_1149_p0;
wire  signed [32:0] p_Val2_32_2_fu_1149_p1;
wire    ap_block_pp0_stage5;
wire   [31:0] tmp_85_2_fu_1163_p1;
wire   [31:0] tmp_89_2_fu_1171_p1;
wire   [31:0] p_Val2_28_2_fu_1166_p2;
wire   [31:0] p_Val2_31_2_fu_1174_p2;
wire  signed [32:0] tmp_92_2_fu_1179_p1;
wire  signed [32:0] tmp_93_2_fu_1183_p1;
wire   [32:0] r_V_2_fu_1187_p2;
wire   [66:0] tmp_973_2_cast_fu_1199_p1;
wire   [66:0] p_Val2_34_2_fu_1202_p2;
wire   [31:0] tmp_101_2_fu_1217_p1;
wire   [31:0] p_Val2_35_2_fu_1207_p4;
wire   [31:0] p_Val2_37_2_fu_1226_p2;
wire    ap_block_pp0_stage6;
wire  signed [31:0] p_Val2_26_3_fu_1241_p0;
wire  signed [63:0] OP1_V_3_3_fu_1238_p1;
wire  signed [31:0] p_Val2_26_3_fu_1241_p1;
wire   [63:0] p_Val2_26_3_fu_1241_p2;
wire  signed [31:0] p_Val2_29_3_fu_1268_p0;
wire  signed [63:0] OP1_V_4_3_fu_1265_p1;
wire  signed [31:0] p_Val2_29_3_fu_1268_p1;
wire   [63:0] p_Val2_29_3_fu_1268_p2;
wire   [32:0] r_V_1_3_fu_1292_p3;
wire  signed [31:0] p_Val2_32_3_fu_1306_p0;
wire  signed [32:0] p_Val2_32_3_fu_1306_p1;
wire    ap_block_pp0_stage7;
wire   [31:0] tmp_85_3_fu_1320_p1;
wire   [31:0] tmp_89_3_fu_1328_p1;
wire   [31:0] p_Val2_28_3_fu_1323_p2;
wire   [31:0] p_Val2_31_3_fu_1331_p2;
wire  signed [32:0] tmp_93_3_fu_1340_p1;
wire  signed [32:0] tmp_92_3_fu_1336_p1;
wire   [32:0] r_V_3_fu_1344_p2;
wire   [66:0] tmp_973_3_cast_fu_1356_p1;
wire   [66:0] p_Val2_34_3_fu_1359_p2;
wire   [31:0] tmp_101_3_fu_1374_p1;
wire   [31:0] p_Val2_35_3_fu_1364_p4;
wire   [31:0] p_Val2_37_3_fu_1383_p2;
wire    ap_block_pp0_stage8;
wire  signed [31:0] p_Val2_26_4_fu_1398_p0;
wire  signed [63:0] OP1_V_3_4_fu_1395_p1;
wire  signed [31:0] p_Val2_26_4_fu_1398_p1;
wire   [63:0] p_Val2_26_4_fu_1398_p2;
wire  signed [31:0] p_Val2_29_4_fu_1425_p0;
wire  signed [63:0] OP1_V_4_4_fu_1422_p1;
wire  signed [31:0] p_Val2_29_4_fu_1425_p1;
wire   [63:0] p_Val2_29_4_fu_1425_p2;
wire   [32:0] r_V_1_4_fu_1449_p3;
wire  signed [31:0] p_Val2_32_4_fu_1463_p0;
wire  signed [32:0] p_Val2_32_4_fu_1463_p1;
wire    ap_block_pp0_stage9;
wire   [31:0] tmp_85_4_fu_1477_p1;
wire   [31:0] tmp_89_4_fu_1485_p1;
wire   [31:0] p_Val2_28_4_fu_1480_p2;
wire   [31:0] p_Val2_31_4_fu_1488_p2;
wire  signed [32:0] tmp_92_4_fu_1493_p1;
wire  signed [32:0] tmp_93_4_fu_1497_p1;
wire   [32:0] r_V_4_fu_1501_p2;
wire   [66:0] tmp_973_4_cast_fu_1513_p1;
wire   [66:0] p_Val2_34_4_fu_1516_p2;
wire   [31:0] tmp_101_4_fu_1531_p1;
wire   [31:0] p_Val2_35_4_fu_1521_p4;
wire   [31:0] p_Val2_37_4_fu_1540_p2;
wire    ap_block_pp0_stage10;
wire  signed [31:0] p_Val2_26_5_fu_1555_p0;
wire  signed [63:0] OP1_V_3_5_fu_1552_p1;
wire  signed [31:0] p_Val2_26_5_fu_1555_p1;
wire   [63:0] p_Val2_26_5_fu_1555_p2;
wire  signed [31:0] p_Val2_29_5_fu_1582_p0;
wire  signed [63:0] OP1_V_4_5_fu_1579_p1;
wire  signed [31:0] p_Val2_29_5_fu_1582_p1;
wire   [63:0] p_Val2_29_5_fu_1582_p2;
wire   [32:0] r_V_1_5_fu_1606_p3;
wire  signed [31:0] p_Val2_32_5_fu_1620_p0;
wire  signed [32:0] p_Val2_32_5_fu_1620_p1;
wire    ap_block_pp0_stage11;
wire   [31:0] tmp_85_5_fu_1634_p1;
wire   [31:0] tmp_89_5_fu_1642_p1;
wire   [31:0] p_Val2_28_5_fu_1637_p2;
wire   [31:0] p_Val2_31_5_fu_1645_p2;
wire  signed [32:0] tmp_92_5_fu_1650_p1;
wire  signed [32:0] tmp_93_5_fu_1654_p1;
wire   [32:0] r_V_5_fu_1658_p2;
wire   [66:0] tmp_973_5_cast_fu_1670_p1;
wire   [66:0] p_Val2_34_5_fu_1673_p2;
wire   [31:0] tmp_101_5_fu_1688_p1;
wire   [31:0] p_Val2_35_5_fu_1678_p4;
wire   [31:0] p_Val2_37_5_fu_1697_p2;
wire    ap_block_pp0_stage12;
wire  signed [31:0] p_Val2_26_6_fu_1712_p0;
wire  signed [63:0] OP1_V_3_6_fu_1709_p1;
wire  signed [31:0] p_Val2_26_6_fu_1712_p1;
wire   [63:0] p_Val2_26_6_fu_1712_p2;
wire  signed [31:0] p_Val2_29_6_fu_1739_p0;
wire  signed [63:0] OP1_V_4_6_fu_1736_p1;
wire  signed [31:0] p_Val2_29_6_fu_1739_p1;
wire   [63:0] p_Val2_29_6_fu_1739_p2;
wire   [32:0] r_V_1_6_fu_1763_p3;
wire  signed [31:0] p_Val2_32_6_fu_1777_p0;
wire  signed [32:0] p_Val2_32_6_fu_1777_p1;
wire   [31:0] tmp_85_6_fu_1809_p1;
wire   [31:0] tmp_89_6_fu_1817_p1;
wire   [31:0] p_Val2_28_6_fu_1812_p2;
wire   [31:0] p_Val2_31_6_fu_1820_p2;
wire  signed [32:0] tmp_93_6_fu_1829_p1;
wire  signed [32:0] tmp_92_6_fu_1825_p1;
wire   [32:0] r_V_6_fu_1833_p2;
wire   [0:0] tmp_94_6_fu_1839_p2;
wire   [66:0] tmp_973_6_cast_fu_1849_p1;
wire   [66:0] p_Val2_34_6_fu_1852_p2;
wire   [31:0] tmp_101_6_fu_1867_p1;
wire   [31:0] p_Val2_35_6_fu_1857_p4;
wire   [31:0] p_Val2_37_6_fu_1876_p2;
wire   [31:0] p_Val2_39_6_fu_1882_p2;
wire  signed [31:0] p_Val2_26_7_fu_1892_p0;
wire  signed [63:0] OP1_V_3_7_fu_1888_p1;
wire  signed [31:0] p_Val2_26_7_fu_1892_p1;
wire   [63:0] p_Val2_26_7_fu_1892_p2;
wire   [0:0] tmp_72_fu_1908_p3;
wire   [31:0] tmp_85_7_fu_1916_p1;
wire   [31:0] p_Val2_27_7_fu_1898_p4;
wire   [31:0] p_Val2_36_6_fu_1870_p2;
wire  signed [31:0] p_Val2_29_7_fu_1930_p0;
wire  signed [63:0] OP1_V_4_7_fu_1926_p1;
wire  signed [31:0] p_Val2_29_7_fu_1930_p1;
wire   [63:0] p_Val2_29_7_fu_1930_p2;
wire   [0:0] tmp_73_fu_1946_p3;
wire   [31:0] tmp_89_7_fu_1954_p1;
wire   [31:0] p_Val2_30_7_fu_1936_p4;
wire   [31:0] p_Val2_28_7_fu_1920_p2;
wire   [31:0] p_Val2_31_7_fu_1958_p2;
wire  signed [32:0] tmp_92_7_fu_1964_p1;
wire  signed [32:0] tmp_93_7_fu_1968_p1;
wire   [32:0] r_V_7_fu_1972_p2;
wire   [0:0] tmp_94_7_fu_1978_p2;
wire   [32:0] r_V_1_7_fu_1988_p3;
wire  signed [31:0] p_Val2_32_7_fu_2004_p0;
wire  signed [32:0] p_Val2_32_7_fu_2004_p1;
wire   [64:0] p_Val2_32_7_fu_2004_p2;
wire   [66:0] tmp_973_7_cast_fu_2010_p1;
wire   [66:0] p_Val2_34_7_fu_2014_p2;
wire   [0:0] tmp_74_fu_2029_p3;
wire   [31:0] tmp_101_7_fu_2037_p1;
wire   [31:0] p_Val2_35_7_fu_2019_p4;
wire   [31:0] p_Val2_37_7_fu_2047_p2;
wire   [31:0] p_Val2_39_7_fu_2053_p2;
wire  signed [31:0] p_Val2_26_8_fu_2063_p0;
wire  signed [63:0] OP1_V_3_8_fu_2059_p1;
wire  signed [31:0] p_Val2_26_8_fu_2063_p1;
wire   [63:0] p_Val2_26_8_fu_2063_p2;
wire   [0:0] tmp_75_fu_2079_p3;
wire   [31:0] tmp_85_8_fu_2087_p1;
wire   [31:0] p_Val2_27_8_fu_2069_p4;
wire   [31:0] p_Val2_36_7_fu_2041_p2;
wire  signed [31:0] p_Val2_29_8_fu_2101_p0;
wire  signed [63:0] OP1_V_4_8_fu_2097_p1;
wire  signed [31:0] p_Val2_29_8_fu_2101_p1;
wire   [63:0] p_Val2_29_8_fu_2101_p2;
wire   [0:0] tmp_76_fu_2117_p3;
wire   [31:0] tmp_89_8_fu_2125_p1;
wire   [31:0] p_Val2_30_8_fu_2107_p4;
wire   [31:0] p_Val2_28_8_fu_2091_p2;
wire   [31:0] p_Val2_31_8_fu_2129_p2;
wire  signed [32:0] tmp_93_8_fu_2139_p1;
wire  signed [32:0] tmp_92_8_fu_2135_p1;
wire   [32:0] r_V_8_fu_2143_p2;
wire   [0:0] tmp_94_8_fu_2149_p2;
wire   [15:0] tmp_95_6_fu_1845_p1;
wire   [1:0] tmp_95_4_cast_fu_1803_p1;
wire   [1:0] tmp_95_5_cast_fu_1806_p1;
wire   [1:0] tmp_95_7_cast_fu_1984_p1;
wire   [1:0] tmp2_fu_2165_p2;
wire   [1:0] tmp_95_8_cast_fu_2155_p1;
wire   [1:0] tmp_95_1_cast_fu_1797_p1;
wire   [1:0] tmp_95_2_cast_fu_1800_p1;
wire   [1:0] tmp6_fu_2177_p2;
wire   [32:0] r_V_1_8_fu_2189_p3;
wire  signed [31:0] p_Val2_32_8_fu_2205_p0;
wire  signed [32:0] p_Val2_32_8_fu_2205_p1;
wire   [64:0] p_Val2_32_8_fu_2205_p2;
wire   [66:0] tmp_973_8_cast_fu_2211_p1;
wire   [66:0] p_Val2_34_8_fu_2215_p2;
wire   [0:0] tmp_77_fu_2230_p3;
wire   [31:0] tmp_101_8_fu_2238_p1;
wire   [31:0] p_Val2_35_8_fu_2220_p4;
wire   [31:0] p_Val2_37_8_fu_2248_p2;
wire   [31:0] p_Val2_39_8_fu_2254_p2;
wire  signed [31:0] p_Val2_26_9_fu_2264_p0;
wire  signed [63:0] OP1_V_3_9_fu_2260_p1;
wire  signed [31:0] p_Val2_26_9_fu_2264_p1;
wire   [63:0] p_Val2_26_9_fu_2264_p2;
wire   [0:0] tmp_78_fu_2280_p3;
wire   [31:0] tmp_85_9_fu_2288_p1;
wire   [31:0] p_Val2_27_9_fu_2270_p4;
wire   [31:0] p_Val2_36_8_fu_2242_p2;
wire  signed [31:0] p_Val2_29_9_fu_2302_p0;
wire  signed [63:0] OP1_V_4_9_fu_2298_p1;
wire  signed [31:0] p_Val2_29_9_fu_2302_p1;
wire   [63:0] p_Val2_29_9_fu_2302_p2;
wire   [0:0] tmp_79_fu_2318_p3;
wire   [31:0] tmp_89_9_fu_2326_p1;
wire   [31:0] p_Val2_30_9_fu_2308_p4;
wire   [31:0] p_Val2_28_9_fu_2292_p2;
wire   [31:0] p_Val2_31_9_fu_2330_p2;
wire  signed [32:0] tmp_93_9_fu_2340_p1;
wire  signed [32:0] tmp_92_9_fu_2336_p1;
wire   [32:0] r_V_9_fu_2344_p2;
wire   [32:0] r_V_1_9_fu_2356_p3;
wire  signed [31:0] p_Val2_32_9_fu_2372_p0;
wire  signed [32:0] p_Val2_32_9_fu_2372_p1;
wire   [64:0] p_Val2_32_9_fu_2372_p2;
wire   [66:0] tmp_973_9_cast_fu_2378_p1;
wire   [66:0] p_Val2_34_9_fu_2382_p2;
wire   [0:0] tmp_80_fu_2397_p3;
wire   [31:0] tmp_101_9_fu_2405_p1;
wire   [31:0] p_Val2_35_9_fu_2387_p4;
wire   [31:0] p_Val2_37_9_fu_2415_p2;
wire   [31:0] p_Val2_39_9_fu_2421_p2;
wire  signed [31:0] p_Val2_26_s_fu_2431_p0;
wire  signed [63:0] OP1_V_3_s_fu_2427_p1;
wire  signed [31:0] p_Val2_26_s_fu_2431_p1;
wire   [63:0] p_Val2_26_s_fu_2431_p2;
wire   [0:0] tmp_81_fu_2447_p3;
wire   [31:0] tmp_85_s_fu_2455_p1;
wire   [31:0] p_Val2_27_s_fu_2437_p4;
wire   [31:0] p_Val2_36_9_fu_2409_p2;
wire  signed [31:0] p_Val2_29_s_fu_2469_p0;
wire  signed [63:0] OP1_V_4_s_fu_2465_p1;
wire  signed [31:0] p_Val2_29_s_fu_2469_p1;
wire   [63:0] p_Val2_29_s_fu_2469_p2;
wire   [0:0] tmp_82_fu_2485_p3;
wire   [31:0] tmp_89_s_fu_2493_p1;
wire   [31:0] p_Val2_30_s_fu_2475_p4;
wire   [31:0] p_Val2_28_s_fu_2459_p2;
wire   [31:0] p_Val2_31_s_fu_2497_p2;
wire  signed [32:0] tmp_92_s_fu_2503_p1;
wire  signed [32:0] tmp_93_s_fu_2507_p1;
wire   [32:0] r_V_10_fu_2511_p2;
wire   [32:0] r_V_1_s_fu_2523_p3;
wire  signed [31:0] p_Val2_32_s_fu_2539_p0;
wire  signed [32:0] p_Val2_32_s_fu_2539_p1;
wire   [64:0] p_Val2_32_s_fu_2539_p2;
wire   [66:0] tmp_973_cast_fu_2545_p1;
wire   [66:0] p_Val2_34_s_fu_2549_p2;
wire   [0:0] tmp_83_fu_2564_p3;
wire   [31:0] tmp_101_s_fu_2572_p1;
wire   [31:0] p_Val2_35_s_fu_2554_p4;
wire   [31:0] p_Val2_37_s_fu_2582_p2;
wire   [31:0] p_Val2_39_s_fu_2588_p2;
wire  signed [31:0] p_Val2_26_10_fu_2598_p0;
wire  signed [63:0] OP1_V_3_10_fu_2594_p1;
wire  signed [31:0] p_Val2_26_10_fu_2598_p1;
wire   [63:0] p_Val2_26_10_fu_2598_p2;
wire   [0:0] tmp_84_fu_2614_p3;
wire   [31:0] tmp_85_10_fu_2622_p1;
wire   [31:0] p_Val2_27_10_fu_2604_p4;
wire   [31:0] p_Val2_36_s_fu_2576_p2;
wire  signed [31:0] p_Val2_29_10_fu_2636_p0;
wire  signed [63:0] OP1_V_4_10_fu_2632_p1;
wire  signed [31:0] p_Val2_29_10_fu_2636_p1;
wire   [63:0] p_Val2_29_10_fu_2636_p2;
wire   [0:0] tmp_85_fu_2652_p3;
wire   [31:0] tmp_89_10_fu_2660_p1;
wire   [31:0] p_Val2_30_10_fu_2642_p4;
wire   [31:0] p_Val2_28_10_fu_2626_p2;
wire   [31:0] p_Val2_31_10_fu_2664_p2;
wire  signed [32:0] tmp_93_10_fu_2674_p1;
wire  signed [32:0] tmp_92_10_fu_2670_p1;
wire   [32:0] r_V_11_fu_2678_p2;
wire   [32:0] r_V_1_10_fu_2690_p3;
wire  signed [31:0] p_Val2_32_10_fu_2706_p0;
wire  signed [32:0] p_Val2_32_10_fu_2706_p1;
wire   [64:0] p_Val2_32_10_fu_2706_p2;
wire   [66:0] tmp_973_10_cast_fu_2712_p1;
wire   [66:0] p_Val2_34_10_fu_2716_p2;
wire   [0:0] tmp_86_fu_2731_p3;
wire   [31:0] tmp_101_10_fu_2739_p1;
wire   [31:0] p_Val2_35_10_fu_2721_p4;
wire   [31:0] p_Val2_37_10_fu_2749_p2;
wire   [31:0] p_Val2_39_10_fu_2755_p2;
wire  signed [31:0] p_Val2_26_11_fu_2765_p0;
wire  signed [63:0] OP1_V_3_11_fu_2761_p1;
wire  signed [31:0] p_Val2_26_11_fu_2765_p1;
wire   [63:0] p_Val2_26_11_fu_2765_p2;
wire   [0:0] tmp_87_fu_2781_p3;
wire   [31:0] tmp_85_11_fu_2789_p1;
wire   [31:0] p_Val2_27_11_fu_2771_p4;
wire   [31:0] p_Val2_36_10_fu_2743_p2;
wire  signed [31:0] p_Val2_29_11_fu_2803_p0;
wire  signed [63:0] OP1_V_4_11_fu_2799_p1;
wire  signed [31:0] p_Val2_29_11_fu_2803_p1;
wire   [63:0] p_Val2_29_11_fu_2803_p2;
wire   [0:0] tmp_88_fu_2819_p3;
wire   [31:0] tmp_89_11_fu_2827_p1;
wire   [31:0] p_Val2_30_11_fu_2809_p4;
wire   [31:0] p_Val2_28_11_fu_2793_p2;
wire   [31:0] p_Val2_31_11_fu_2831_p2;
wire  signed [32:0] tmp_93_11_fu_2841_p1;
wire  signed [32:0] tmp_92_11_fu_2837_p1;
wire   [32:0] r_V_12_fu_2845_p2;
wire   [32:0] r_V_1_11_fu_2857_p3;
wire  signed [31:0] p_Val2_32_11_fu_2873_p0;
wire  signed [32:0] p_Val2_32_11_fu_2873_p1;
wire   [64:0] p_Val2_32_11_fu_2873_p2;
wire   [66:0] tmp_973_11_cast_fu_2879_p1;
wire   [66:0] p_Val2_34_11_fu_2883_p2;
wire   [0:0] tmp_89_fu_2898_p3;
wire   [31:0] tmp_101_11_fu_2906_p1;
wire   [31:0] p_Val2_35_11_fu_2888_p4;
wire   [31:0] p_Val2_37_11_fu_2916_p2;
wire   [15:0] tmp39_cast_fu_2934_p1;
wire   [1:0] tmp_79_cast_fu_2928_p1;
wire   [1:0] tmp_95_3_cast_fu_2931_p1;
wire   [1:0] tmp5_fu_2942_p2;
wire   [2:0] tmp42_cast_fu_2948_p1;
wire   [2:0] tmp43_cast_fu_2952_p1;
wire   [2:0] tmp8_fu_2955_p2;
wire   [15:0] tmp4_fu_2937_p2;
wire   [15:0] tmp41_cast_fu_2961_p1;
wire   [15:0] tmp_95_9_fu_2971_p1;
wire   [1:0] tmp_95_10_cast_fu_2977_p1;
wire   [1:0] tmp_95_cast_fu_2974_p1;
wire   [1:0] tmp10_fu_2985_p2;
wire   [15:0] tmp9_fu_2980_p2;
wire   [15:0] tmp47_cast_fu_2991_p1;
wire   [15:0] tmp_95_s_fu_3001_p1;
wire   [15:0] tmp_96_s_fu_2995_p2;
reg   [18:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage9_subdone;
wire    ap_block_pp0_stage10_subdone;
wire    ap_block_pp0_stage11_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 19'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

mandelbrot_fpext_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mandelbrot_fpext_bkb_U1(
    .din0(grp_fu_227_p0),
    .dout(grp_fu_227_p1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage12_subdone) & (exitcond_9_fu_1791_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage12_subdone) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_9_reg_3514 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        i_reg_204 <= i_1_s_fu_3010_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        i_reg_204 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_9_reg_3514 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        mandelbrot_float_fl_reg_216 <= tmp_96_1_fu_3004_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mandelbrot_float_fl_reg_216 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_18_fu_551_p2 == 1'd1))) begin
        p_3_reg_170 <= 32'd0;
    end else if (((tmp_33_reg_3181 == 1'd0) & (tmp_18_reg_3116 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        p_3_reg_170 <= tmp_50_s_fu_743_p3;
    end else if (((tmp_18_reg_3116 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (tmp_33_reg_3181 == 1'd1))) begin
        p_3_reg_170 <= tmp_43_mux_fu_737_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_9_reg_3514 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_36_12_reg_184 <= p_Val2_36_11_fu_2910_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        p_Val2_36_12_reg_184 <= ap_phi_mux_p_3_phi_fu_174_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_9_reg_3514 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_39_12_reg_194 <= p_Val2_39_11_fu_2922_p2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        p_Val2_39_12_reg_194 <= z_re_V_load_reg_143;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (tmp_18_fu_551_p2 == 1'd1))) begin
        z0_im_V_load_reg_157 <= 32'd0;
    end else if ((((tmp_33_reg_3181 == 1'd0) & (tmp_18_reg_3116 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((tmp_18_reg_3116 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (tmp_33_reg_3181 == 1'd1)))) begin
        z0_im_V_load_reg_157 <= p_2_fu_727_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_291_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        z0_re_V_load_reg_129 <= 32'd0;
    end else if ((((tmp_15_reg_3099 == 1'd0) & (tmp_7_reg_3034 == 1'd0) & (1'b1 == ap_CS_fsm_state3)) | ((tmp_15_reg_3099 == 1'd1) & (tmp_7_reg_3034 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        z0_re_V_load_reg_129 <= p_s_fu_467_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_291_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        z_re_V_load_reg_143 <= 32'd0;
    end else if (((tmp_15_reg_3099 == 1'd0) & (tmp_7_reg_3034 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        z_re_V_load_reg_143 <= tmp_15_s_fu_483_p3;
    end else if (((tmp_15_reg_3099 == 1'd1) & (tmp_7_reg_3034 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        z_re_V_load_reg_143 <= tmp_4_mux_fu_477_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_18_fu_551_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        F2_1_reg_3120 <= F2_1_fu_557_p2;
        tmp_19_reg_3128 <= tmp_19_fu_563_p2;
        tmp_20_reg_3134 <= tmp_20_fu_569_p2;
        tmp_21_reg_3140 <= tmp_21_fu_575_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_291_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        F2_reg_3038 <= F2_fu_297_p2;
        tmp_1_reg_3058 <= tmp_1_fu_315_p2;
        tmp_9_reg_3046 <= tmp_9_fu_303_p2;
        tmp_s_reg_3052 <= tmp_s_fu_309_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage12_11001) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        exitcond_9_reg_3514 <= exitcond_9_fu_1791_p2;
        p_Val2_27_6_reg_3484 <= {{p_Val2_26_6_fu_1712_p2[59:28]}};
        p_Val2_30_6_reg_3494 <= {{p_Val2_29_6_fu_1739_p2[59:28]}};
        p_Val2_32_6_reg_3504[64 : 1] <= p_Val2_32_6_fu_1777_p2[64 : 1];
        tmp_69_reg_3489 <= p_Val2_26_6_fu_1712_p2[32'd27];
        tmp_70_reg_3499 <= p_Val2_29_6_fu_1739_p2[32'd27];
        tmp_71_reg_3509 <= p_Val2_32_6_fu_1777_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        icmp5_reg_3164 <= icmp5_fu_614_p2;
        p_Val2_8_reg_3170 <= p_Val2_8_fu_680_p2;
        sel_tmp10_reg_3176 <= sel_tmp10_fu_686_p2;
        sh_amt_1_cast_reg_3145 <= sh_amt_1_cast_fu_586_p1;
        tmp_22_reg_3150 <= tmp_22_fu_590_p2;
        tmp_33_reg_3181 <= tmp_33_fu_691_p2;
        tmp_47_reg_3157 <= tmp_47_fu_595_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_reg_3082 <= icmp_fu_354_p2;
        p_Val2_5_reg_3088 <= p_Val2_5_fu_420_p2;
        sel_tmp6_reg_3094 <= sel_tmp6_fu_426_p2;
        sh_amt_cast_reg_3063 <= sh_amt_cast_fu_326_p1;
        tmp_15_reg_3099 <= tmp_15_fu_431_p2;
        tmp_24_reg_3075 <= tmp_24_fu_335_p1;
        tmp_3_reg_3068 <= tmp_3_fu_330_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        isneg_1_reg_3103 <= p_Val2_21_fu_491_p1[32'd63];
        man_V_11_reg_3109 <= man_V_11_fu_543_p3;
        tmp_18_reg_3116 <= tmp_18_fu_551_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        isneg_reg_3021 <= p_Val2_s_fu_231_p1[32'd63];
        man_V_4_reg_3027 <= man_V_4_fu_283_p3;
        tmp_7_reg_3034 <= tmp_7_fu_291_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_11_reg_3222[64 : 1] <= p_Val2_11_fu_835_p2[64 : 1];
        p_Val2_1_reg_3202 <= {{p_Val2_s_8_fu_767_p2[59:28]}};
        p_Val2_9_reg_3212 <= {{p_Val2_3_fu_795_p2[59:28]}};
        tmp1_reg_3518 <= tmp1_fu_2159_p2;
        tmp3_reg_3523 <= tmp3_fu_2171_p2;
        tmp7_reg_3528 <= tmp7_fu_2183_p2;
        tmp_51_reg_3207 <= p_Val2_s_8_fu_767_p2[32'd27];
        tmp_52_reg_3217 <= p_Val2_3_fu_795_p2[32'd27];
        tmp_53_reg_3227 <= p_Val2_11_fu_835_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        p_Val2_14_reg_3237 <= p_Val2_14_fu_906_p2;
        p_Val2_16_reg_3243 <= p_Val2_16_fu_918_p2;
        tmp_40_reg_3232 <= tmp_40_fu_879_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        p_Val2_27_1_reg_3249 <= {{p_Val2_26_1_fu_927_p2[59:28]}};
        p_Val2_30_1_reg_3259 <= {{p_Val2_29_1_fu_954_p2[59:28]}};
        p_Val2_32_1_reg_3269[64 : 1] <= p_Val2_32_1_fu_992_p2[64 : 1];
        tmp_54_reg_3254 <= p_Val2_26_1_fu_927_p2[32'd27];
        tmp_55_reg_3264 <= p_Val2_29_1_fu_954_p2[32'd27];
        tmp_56_reg_3274 <= p_Val2_32_1_fu_992_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        p_Val2_27_2_reg_3296 <= {{p_Val2_26_2_fu_1084_p2[59:28]}};
        p_Val2_30_2_reg_3306 <= {{p_Val2_29_2_fu_1111_p2[59:28]}};
        p_Val2_32_2_reg_3316[64 : 1] <= p_Val2_32_2_fu_1149_p2[64 : 1];
        tmp_57_reg_3301 <= p_Val2_26_2_fu_1084_p2[32'd27];
        tmp_58_reg_3311 <= p_Val2_29_2_fu_1111_p2[32'd27];
        tmp_59_reg_3321 <= p_Val2_32_2_fu_1149_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        p_Val2_27_3_reg_3343 <= {{p_Val2_26_3_fu_1241_p2[59:28]}};
        p_Val2_30_3_reg_3353 <= {{p_Val2_29_3_fu_1268_p2[59:28]}};
        p_Val2_32_3_reg_3363[64 : 1] <= p_Val2_32_3_fu_1306_p2[64 : 1];
        tmp_60_reg_3348 <= p_Val2_26_3_fu_1241_p2[32'd27];
        tmp_61_reg_3358 <= p_Val2_29_3_fu_1268_p2[32'd27];
        tmp_62_reg_3368 <= p_Val2_32_3_fu_1306_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        p_Val2_27_4_reg_3390 <= {{p_Val2_26_4_fu_1398_p2[59:28]}};
        p_Val2_30_4_reg_3400 <= {{p_Val2_29_4_fu_1425_p2[59:28]}};
        p_Val2_32_4_reg_3410[64 : 1] <= p_Val2_32_4_fu_1463_p2[64 : 1];
        tmp_63_reg_3395 <= p_Val2_26_4_fu_1398_p2[32'd27];
        tmp_64_reg_3405 <= p_Val2_29_4_fu_1425_p2[32'd27];
        tmp_65_reg_3415 <= p_Val2_32_4_fu_1463_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        p_Val2_27_5_reg_3437 <= {{p_Val2_26_5_fu_1555_p2[59:28]}};
        p_Val2_30_5_reg_3447 <= {{p_Val2_29_5_fu_1582_p2[59:28]}};
        p_Val2_32_5_reg_3457[64 : 1] <= p_Val2_32_5_fu_1620_p2[64 : 1];
        tmp_66_reg_3442 <= p_Val2_26_5_fu_1555_p2[32'd27];
        tmp_67_reg_3452 <= p_Val2_29_5_fu_1582_p2[32'd27];
        tmp_68_reg_3462 <= p_Val2_32_5_fu_1620_p2[32'd27];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        p_Val2_36_1_reg_3284 <= p_Val2_36_1_fu_1063_p2;
        p_Val2_39_1_reg_3290 <= p_Val2_39_1_fu_1075_p2;
        tmp_94_1_reg_3279 <= tmp_94_1_fu_1036_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        p_Val2_36_2_reg_3331 <= p_Val2_36_2_fu_1220_p2;
        p_Val2_39_2_reg_3337 <= p_Val2_39_2_fu_1232_p2;
        tmp_94_2_reg_3326 <= tmp_94_2_fu_1193_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        p_Val2_36_3_reg_3378 <= p_Val2_36_3_fu_1377_p2;
        p_Val2_39_3_reg_3384 <= p_Val2_39_3_fu_1389_p2;
        tmp_94_3_reg_3373 <= tmp_94_3_fu_1350_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        p_Val2_36_4_reg_3425 <= p_Val2_36_4_fu_1534_p2;
        p_Val2_39_4_reg_3431 <= p_Val2_39_4_fu_1546_p2;
        tmp_94_4_reg_3420 <= tmp_94_4_fu_1507_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage11_11001) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        p_Val2_36_5_reg_3472 <= p_Val2_36_5_fu_1691_p2;
        p_Val2_39_5_reg_3478 <= p_Val2_39_5_fu_1703_p2;
        tmp_94_5_reg_3467 <= tmp_94_5_fu_1664_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        tmp_71_cast_cast_reg_3185[66 : 28] <= tmp_71_cast_cast_fu_759_p1[66 : 28];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_9_reg_3514 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_94_10_reg_3543 <= tmp_94_10_fu_2684_p2;
        tmp_94_11_reg_3548 <= tmp_94_11_fu_2851_p2;
        tmp_94_9_reg_3533 <= tmp_94_9_fu_2350_p2;
        tmp_94_s_reg_3538 <= tmp_94_s_fu_2517_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        tmp_96_8_reg_3563 <= tmp_96_8_fu_2965_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_18_reg_3116 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        if ((tmp_33_reg_3181 == 1'd0)) begin
            ap_phi_mux_p_3_phi_fu_174_p6 = tmp_50_s_fu_743_p3;
        end else if ((tmp_33_reg_3181 == 1'd1)) begin
            ap_phi_mux_p_3_phi_fu_174_p6 = tmp_43_mux_fu_737_p3;
        end else begin
            ap_phi_mux_p_3_phi_fu_174_p6 = p_3_reg_170;
        end
    end else begin
        ap_phi_mux_p_3_phi_fu_174_p6 = p_3_reg_170;
    end
end

always @ (*) begin
    if (((exitcond_9_reg_3514 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_p_Val2_36_12_phi_fu_187_p4 = p_Val2_36_11_fu_2910_p2;
    end else begin
        ap_phi_mux_p_Val2_36_12_phi_fu_187_p4 = p_Val2_36_12_reg_184;
    end
end

always @ (*) begin
    if (((exitcond_9_reg_3514 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_p_Val2_39_12_phi_fu_197_p4 = p_Val2_39_11_fu_2922_p2;
    end else begin
        ap_phi_mux_p_Val2_39_12_phi_fu_197_p4 = p_Val2_39_12_reg_194;
    end
end

always @ (*) begin
    if ((((tmp_33_reg_3181 == 1'd0) & (tmp_18_reg_3116 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((tmp_18_reg_3116 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (tmp_33_reg_3181 == 1'd1)))) begin
        ap_phi_mux_z0_im_V_load_phi_fu_161_p6 = p_2_fu_727_p3;
    end else begin
        ap_phi_mux_z0_im_V_load_phi_fu_161_p6 = z0_im_V_load_reg_157;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_227_p0 = im;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_227_p0 = re;
    end else begin
        grp_fu_227_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        outp_ap_vld = 1'b1;
    end else begin
        outp_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((tmp_7_fu_291_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if (((tmp_7_fu_291_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (tmp_18_fu_551_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((~((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign F2_1_fu_557_p2 = (12'd1075 - tmp_16_fu_517_p1);

assign F2_fu_297_p2 = (12'd1075 - tmp_2_fu_257_p1);

assign OP1_V_3_10_fu_2594_p1 = $signed(p_Val2_39_s_fu_2588_p2);

assign OP1_V_3_11_fu_2761_p1 = $signed(p_Val2_39_10_fu_2755_p2);

assign OP1_V_3_1_fu_924_p1 = $signed(p_Val2_16_reg_3243);

assign OP1_V_3_2_fu_1081_p1 = $signed(p_Val2_39_1_reg_3290);

assign OP1_V_3_3_fu_1238_p1 = $signed(p_Val2_39_2_reg_3337);

assign OP1_V_3_4_fu_1395_p1 = $signed(p_Val2_39_3_reg_3384);

assign OP1_V_3_5_fu_1552_p1 = $signed(p_Val2_39_4_reg_3431);

assign OP1_V_3_6_fu_1709_p1 = $signed(p_Val2_39_5_reg_3478);

assign OP1_V_3_7_fu_1888_p1 = $signed(p_Val2_39_6_fu_1882_p2);

assign OP1_V_3_8_fu_2059_p1 = $signed(p_Val2_39_7_fu_2053_p2);

assign OP1_V_3_9_fu_2260_p1 = $signed(p_Val2_39_8_fu_2254_p2);

assign OP1_V_3_fu_763_p1 = $signed(ap_phi_mux_p_Val2_39_12_phi_fu_197_p4);

assign OP1_V_3_s_fu_2427_p1 = $signed(p_Val2_39_9_fu_2421_p2);

assign OP1_V_4_10_fu_2632_p1 = $signed(p_Val2_36_s_fu_2576_p2);

assign OP1_V_4_11_fu_2799_p1 = $signed(p_Val2_36_10_fu_2743_p2);

assign OP1_V_4_1_fu_951_p1 = $signed(p_Val2_14_reg_3237);

assign OP1_V_4_2_fu_1108_p1 = $signed(p_Val2_36_1_reg_3284);

assign OP1_V_4_3_fu_1265_p1 = $signed(p_Val2_36_2_reg_3331);

assign OP1_V_4_4_fu_1422_p1 = $signed(p_Val2_36_3_reg_3378);

assign OP1_V_4_5_fu_1579_p1 = $signed(p_Val2_36_4_reg_3425);

assign OP1_V_4_6_fu_1736_p1 = $signed(p_Val2_36_5_reg_3472);

assign OP1_V_4_7_fu_1926_p1 = $signed(p_Val2_36_6_fu_1870_p2);

assign OP1_V_4_8_fu_2097_p1 = $signed(p_Val2_36_7_fu_2041_p2);

assign OP1_V_4_9_fu_2298_p1 = $signed(p_Val2_36_8_fu_2242_p2);

assign OP1_V_4_fu_791_p1 = $signed(ap_phi_mux_p_Val2_36_12_phi_fu_187_p4);

assign OP1_V_4_s_fu_2465_p1 = $signed(p_Val2_36_9_fu_2409_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage8_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage9_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage10_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage11_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage12_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign exitcond_9_fu_1791_p2 = ((i_reg_204 == 8'd247) ? 1'b1 : 1'b0);

assign exp_tmp_V_1_fu_507_p4 = {{p_Val2_21_fu_491_p1[62:52]}};

assign exp_tmp_V_fu_247_p4 = {{p_Val2_s_fu_231_p1[62:52]}};

assign i_1_s_fu_3010_p2 = (i_reg_204 + 8'd13);

assign icmp5_fu_614_p2 = ((tmp_48_fu_604_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_fu_354_p2 = ((tmp_26_fu_344_p4 == 7'd0) ? 1'b1 : 1'b0);

assign isneg_1_fu_499_p3 = p_Val2_21_fu_491_p1[32'd63];

assign isneg_fu_239_p3 = p_Val2_s_fu_231_p1[32'd63];

assign man_V_10_fu_533_p1 = tmp_17_fu_525_p3;

assign man_V_11_fu_543_p3 = ((isneg_1_fu_499_p3[0:0] === 1'b1) ? man_V_6_fu_537_p2 : man_V_10_fu_533_p1);

assign man_V_1_fu_277_p2 = (54'd0 - man_V_fu_273_p1);

assign man_V_4_fu_283_p3 = ((isneg_fu_239_p3[0:0] === 1'b1) ? man_V_1_fu_277_p2 : man_V_fu_273_p1);

assign man_V_6_fu_537_p2 = (54'd0 - man_V_10_fu_533_p1);

assign man_V_fu_273_p1 = tmp_fu_265_p3;

assign outp = tmp_96_8_reg_3563;

assign p_2_fu_727_p3 = ((sel_tmp11_fu_723_p2[0:0] === 1'b1) ? tmp_28_fu_696_p2 : sel_tmp9_fu_716_p3);

assign p_Val2_0_i_i_i1_fu_373_p3 = ((isneg_reg_3021[0:0] === 1'b1) ? 32'd4294967295 : 32'd0);

assign p_Val2_0_i_i_i5_fu_633_p3 = ((isneg_1_reg_3103[0:0] === 1'b1) ? 32'd4294967295 : 32'd0);

assign p_Val2_10_fu_860_p2 = (tmp_37_fu_857_p1 + p_Val2_9_reg_3212);

assign p_Val2_11_fu_835_p0 = ap_phi_mux_p_Val2_36_12_phi_fu_187_p4;

assign p_Val2_11_fu_835_p1 = r_V_1_fu_819_p3;

assign p_Val2_11_fu_835_p2 = ($signed(p_Val2_11_fu_835_p0) * $signed(p_Val2_11_fu_835_p1));

assign p_Val2_12_fu_888_p2 = ($signed(tmp_42_cast_fu_885_p1) + $signed(tmp_71_cast_cast_reg_3185));

assign p_Val2_13_fu_893_p4 = {{p_Val2_12_fu_888_p2[59:28]}};

assign p_Val2_14_fu_906_p2 = (tmp_41_fu_903_p1 + p_Val2_13_fu_893_p4);

assign p_Val2_15_fu_912_p2 = (p_Val2_2_fu_852_p2 - p_Val2_10_fu_860_p2);

assign p_Val2_16_fu_918_p2 = (z0_re_V_load_reg_129 + p_Val2_15_fu_912_p2);

assign p_Val2_21_fu_491_p1 = grp_fu_227_p1;

assign p_Val2_26_10_fu_2598_p0 = OP1_V_3_10_fu_2594_p1;

assign p_Val2_26_10_fu_2598_p1 = OP1_V_3_10_fu_2594_p1;

assign p_Val2_26_10_fu_2598_p2 = ($signed(p_Val2_26_10_fu_2598_p0) * $signed(p_Val2_26_10_fu_2598_p1));

assign p_Val2_26_11_fu_2765_p0 = OP1_V_3_11_fu_2761_p1;

assign p_Val2_26_11_fu_2765_p1 = OP1_V_3_11_fu_2761_p1;

assign p_Val2_26_11_fu_2765_p2 = ($signed(p_Val2_26_11_fu_2765_p0) * $signed(p_Val2_26_11_fu_2765_p1));

assign p_Val2_26_1_fu_927_p0 = OP1_V_3_1_fu_924_p1;

assign p_Val2_26_1_fu_927_p1 = OP1_V_3_1_fu_924_p1;

assign p_Val2_26_1_fu_927_p2 = ($signed(p_Val2_26_1_fu_927_p0) * $signed(p_Val2_26_1_fu_927_p1));

assign p_Val2_26_2_fu_1084_p0 = OP1_V_3_2_fu_1081_p1;

assign p_Val2_26_2_fu_1084_p1 = OP1_V_3_2_fu_1081_p1;

assign p_Val2_26_2_fu_1084_p2 = ($signed(p_Val2_26_2_fu_1084_p0) * $signed(p_Val2_26_2_fu_1084_p1));

assign p_Val2_26_3_fu_1241_p0 = OP1_V_3_3_fu_1238_p1;

assign p_Val2_26_3_fu_1241_p1 = OP1_V_3_3_fu_1238_p1;

assign p_Val2_26_3_fu_1241_p2 = ($signed(p_Val2_26_3_fu_1241_p0) * $signed(p_Val2_26_3_fu_1241_p1));

assign p_Val2_26_4_fu_1398_p0 = OP1_V_3_4_fu_1395_p1;

assign p_Val2_26_4_fu_1398_p1 = OP1_V_3_4_fu_1395_p1;

assign p_Val2_26_4_fu_1398_p2 = ($signed(p_Val2_26_4_fu_1398_p0) * $signed(p_Val2_26_4_fu_1398_p1));

assign p_Val2_26_5_fu_1555_p0 = OP1_V_3_5_fu_1552_p1;

assign p_Val2_26_5_fu_1555_p1 = OP1_V_3_5_fu_1552_p1;

assign p_Val2_26_5_fu_1555_p2 = ($signed(p_Val2_26_5_fu_1555_p0) * $signed(p_Val2_26_5_fu_1555_p1));

assign p_Val2_26_6_fu_1712_p0 = OP1_V_3_6_fu_1709_p1;

assign p_Val2_26_6_fu_1712_p1 = OP1_V_3_6_fu_1709_p1;

assign p_Val2_26_6_fu_1712_p2 = ($signed(p_Val2_26_6_fu_1712_p0) * $signed(p_Val2_26_6_fu_1712_p1));

assign p_Val2_26_7_fu_1892_p0 = OP1_V_3_7_fu_1888_p1;

assign p_Val2_26_7_fu_1892_p1 = OP1_V_3_7_fu_1888_p1;

assign p_Val2_26_7_fu_1892_p2 = ($signed(p_Val2_26_7_fu_1892_p0) * $signed(p_Val2_26_7_fu_1892_p1));

assign p_Val2_26_8_fu_2063_p0 = OP1_V_3_8_fu_2059_p1;

assign p_Val2_26_8_fu_2063_p1 = OP1_V_3_8_fu_2059_p1;

assign p_Val2_26_8_fu_2063_p2 = ($signed(p_Val2_26_8_fu_2063_p0) * $signed(p_Val2_26_8_fu_2063_p1));

assign p_Val2_26_9_fu_2264_p0 = OP1_V_3_9_fu_2260_p1;

assign p_Val2_26_9_fu_2264_p1 = OP1_V_3_9_fu_2260_p1;

assign p_Val2_26_9_fu_2264_p2 = ($signed(p_Val2_26_9_fu_2264_p0) * $signed(p_Val2_26_9_fu_2264_p1));

assign p_Val2_26_s_fu_2431_p0 = OP1_V_3_s_fu_2427_p1;

assign p_Val2_26_s_fu_2431_p1 = OP1_V_3_s_fu_2427_p1;

assign p_Val2_26_s_fu_2431_p2 = ($signed(p_Val2_26_s_fu_2431_p0) * $signed(p_Val2_26_s_fu_2431_p1));

assign p_Val2_27_10_fu_2604_p4 = {{p_Val2_26_10_fu_2598_p2[59:28]}};

assign p_Val2_27_11_fu_2771_p4 = {{p_Val2_26_11_fu_2765_p2[59:28]}};

assign p_Val2_27_7_fu_1898_p4 = {{p_Val2_26_7_fu_1892_p2[59:28]}};

assign p_Val2_27_8_fu_2069_p4 = {{p_Val2_26_8_fu_2063_p2[59:28]}};

assign p_Val2_27_9_fu_2270_p4 = {{p_Val2_26_9_fu_2264_p2[59:28]}};

assign p_Val2_27_s_fu_2437_p4 = {{p_Val2_26_s_fu_2431_p2[59:28]}};

assign p_Val2_28_10_fu_2626_p2 = (tmp_85_10_fu_2622_p1 + p_Val2_27_10_fu_2604_p4);

assign p_Val2_28_11_fu_2793_p2 = (tmp_85_11_fu_2789_p1 + p_Val2_27_11_fu_2771_p4);

assign p_Val2_28_1_fu_1009_p2 = (tmp_85_1_fu_1006_p1 + p_Val2_27_1_reg_3249);

assign p_Val2_28_2_fu_1166_p2 = (tmp_85_2_fu_1163_p1 + p_Val2_27_2_reg_3296);

assign p_Val2_28_3_fu_1323_p2 = (tmp_85_3_fu_1320_p1 + p_Val2_27_3_reg_3343);

assign p_Val2_28_4_fu_1480_p2 = (tmp_85_4_fu_1477_p1 + p_Val2_27_4_reg_3390);

assign p_Val2_28_5_fu_1637_p2 = (tmp_85_5_fu_1634_p1 + p_Val2_27_5_reg_3437);

assign p_Val2_28_6_fu_1812_p2 = (tmp_85_6_fu_1809_p1 + p_Val2_27_6_reg_3484);

assign p_Val2_28_7_fu_1920_p2 = (tmp_85_7_fu_1916_p1 + p_Val2_27_7_fu_1898_p4);

assign p_Val2_28_8_fu_2091_p2 = (tmp_85_8_fu_2087_p1 + p_Val2_27_8_fu_2069_p4);

assign p_Val2_28_9_fu_2292_p2 = (tmp_85_9_fu_2288_p1 + p_Val2_27_9_fu_2270_p4);

assign p_Val2_28_s_fu_2459_p2 = (tmp_85_s_fu_2455_p1 + p_Val2_27_s_fu_2437_p4);

assign p_Val2_29_10_fu_2636_p0 = OP1_V_4_10_fu_2632_p1;

assign p_Val2_29_10_fu_2636_p1 = OP1_V_4_10_fu_2632_p1;

assign p_Val2_29_10_fu_2636_p2 = ($signed(p_Val2_29_10_fu_2636_p0) * $signed(p_Val2_29_10_fu_2636_p1));

assign p_Val2_29_11_fu_2803_p0 = OP1_V_4_11_fu_2799_p1;

assign p_Val2_29_11_fu_2803_p1 = OP1_V_4_11_fu_2799_p1;

assign p_Val2_29_11_fu_2803_p2 = ($signed(p_Val2_29_11_fu_2803_p0) * $signed(p_Val2_29_11_fu_2803_p1));

assign p_Val2_29_1_fu_954_p0 = OP1_V_4_1_fu_951_p1;

assign p_Val2_29_1_fu_954_p1 = OP1_V_4_1_fu_951_p1;

assign p_Val2_29_1_fu_954_p2 = ($signed(p_Val2_29_1_fu_954_p0) * $signed(p_Val2_29_1_fu_954_p1));

assign p_Val2_29_2_fu_1111_p0 = OP1_V_4_2_fu_1108_p1;

assign p_Val2_29_2_fu_1111_p1 = OP1_V_4_2_fu_1108_p1;

assign p_Val2_29_2_fu_1111_p2 = ($signed(p_Val2_29_2_fu_1111_p0) * $signed(p_Val2_29_2_fu_1111_p1));

assign p_Val2_29_3_fu_1268_p0 = OP1_V_4_3_fu_1265_p1;

assign p_Val2_29_3_fu_1268_p1 = OP1_V_4_3_fu_1265_p1;

assign p_Val2_29_3_fu_1268_p2 = ($signed(p_Val2_29_3_fu_1268_p0) * $signed(p_Val2_29_3_fu_1268_p1));

assign p_Val2_29_4_fu_1425_p0 = OP1_V_4_4_fu_1422_p1;

assign p_Val2_29_4_fu_1425_p1 = OP1_V_4_4_fu_1422_p1;

assign p_Val2_29_4_fu_1425_p2 = ($signed(p_Val2_29_4_fu_1425_p0) * $signed(p_Val2_29_4_fu_1425_p1));

assign p_Val2_29_5_fu_1582_p0 = OP1_V_4_5_fu_1579_p1;

assign p_Val2_29_5_fu_1582_p1 = OP1_V_4_5_fu_1579_p1;

assign p_Val2_29_5_fu_1582_p2 = ($signed(p_Val2_29_5_fu_1582_p0) * $signed(p_Val2_29_5_fu_1582_p1));

assign p_Val2_29_6_fu_1739_p0 = OP1_V_4_6_fu_1736_p1;

assign p_Val2_29_6_fu_1739_p1 = OP1_V_4_6_fu_1736_p1;

assign p_Val2_29_6_fu_1739_p2 = ($signed(p_Val2_29_6_fu_1739_p0) * $signed(p_Val2_29_6_fu_1739_p1));

assign p_Val2_29_7_fu_1930_p0 = OP1_V_4_7_fu_1926_p1;

assign p_Val2_29_7_fu_1930_p1 = OP1_V_4_7_fu_1926_p1;

assign p_Val2_29_7_fu_1930_p2 = ($signed(p_Val2_29_7_fu_1930_p0) * $signed(p_Val2_29_7_fu_1930_p1));

assign p_Val2_29_8_fu_2101_p0 = OP1_V_4_8_fu_2097_p1;

assign p_Val2_29_8_fu_2101_p1 = OP1_V_4_8_fu_2097_p1;

assign p_Val2_29_8_fu_2101_p2 = ($signed(p_Val2_29_8_fu_2101_p0) * $signed(p_Val2_29_8_fu_2101_p1));

assign p_Val2_29_9_fu_2302_p0 = OP1_V_4_9_fu_2298_p1;

assign p_Val2_29_9_fu_2302_p1 = OP1_V_4_9_fu_2298_p1;

assign p_Val2_29_9_fu_2302_p2 = ($signed(p_Val2_29_9_fu_2302_p0) * $signed(p_Val2_29_9_fu_2302_p1));

assign p_Val2_29_s_fu_2469_p0 = OP1_V_4_s_fu_2465_p1;

assign p_Val2_29_s_fu_2469_p1 = OP1_V_4_s_fu_2465_p1;

assign p_Val2_29_s_fu_2469_p2 = ($signed(p_Val2_29_s_fu_2469_p0) * $signed(p_Val2_29_s_fu_2469_p1));

assign p_Val2_2_fu_852_p2 = (tmp_35_fu_849_p1 + p_Val2_1_reg_3202);

assign p_Val2_30_10_fu_2642_p4 = {{p_Val2_29_10_fu_2636_p2[59:28]}};

assign p_Val2_30_11_fu_2809_p4 = {{p_Val2_29_11_fu_2803_p2[59:28]}};

assign p_Val2_30_7_fu_1936_p4 = {{p_Val2_29_7_fu_1930_p2[59:28]}};

assign p_Val2_30_8_fu_2107_p4 = {{p_Val2_29_8_fu_2101_p2[59:28]}};

assign p_Val2_30_9_fu_2308_p4 = {{p_Val2_29_9_fu_2302_p2[59:28]}};

assign p_Val2_30_s_fu_2475_p4 = {{p_Val2_29_s_fu_2469_p2[59:28]}};

assign p_Val2_31_10_fu_2664_p2 = (tmp_89_10_fu_2660_p1 + p_Val2_30_10_fu_2642_p4);

assign p_Val2_31_11_fu_2831_p2 = (tmp_89_11_fu_2827_p1 + p_Val2_30_11_fu_2809_p4);

assign p_Val2_31_1_fu_1017_p2 = (tmp_89_1_fu_1014_p1 + p_Val2_30_1_reg_3259);

assign p_Val2_31_2_fu_1174_p2 = (tmp_89_2_fu_1171_p1 + p_Val2_30_2_reg_3306);

assign p_Val2_31_3_fu_1331_p2 = (tmp_89_3_fu_1328_p1 + p_Val2_30_3_reg_3353);

assign p_Val2_31_4_fu_1488_p2 = (tmp_89_4_fu_1485_p1 + p_Val2_30_4_reg_3400);

assign p_Val2_31_5_fu_1645_p2 = (tmp_89_5_fu_1642_p1 + p_Val2_30_5_reg_3447);

assign p_Val2_31_6_fu_1820_p2 = (tmp_89_6_fu_1817_p1 + p_Val2_30_6_reg_3494);

assign p_Val2_31_7_fu_1958_p2 = (tmp_89_7_fu_1954_p1 + p_Val2_30_7_fu_1936_p4);

assign p_Val2_31_8_fu_2129_p2 = (tmp_89_8_fu_2125_p1 + p_Val2_30_8_fu_2107_p4);

assign p_Val2_31_9_fu_2330_p2 = (tmp_89_9_fu_2326_p1 + p_Val2_30_9_fu_2308_p4);

assign p_Val2_31_s_fu_2497_p2 = (tmp_89_s_fu_2493_p1 + p_Val2_30_s_fu_2475_p4);

assign p_Val2_32_10_fu_2706_p0 = p_Val2_36_s_fu_2576_p2;

assign p_Val2_32_10_fu_2706_p1 = r_V_1_10_fu_2690_p3;

assign p_Val2_32_10_fu_2706_p2 = ($signed(p_Val2_32_10_fu_2706_p0) * $signed(p_Val2_32_10_fu_2706_p1));

assign p_Val2_32_11_fu_2873_p0 = p_Val2_36_10_fu_2743_p2;

assign p_Val2_32_11_fu_2873_p1 = r_V_1_11_fu_2857_p3;

assign p_Val2_32_11_fu_2873_p2 = ($signed(p_Val2_32_11_fu_2873_p0) * $signed(p_Val2_32_11_fu_2873_p1));

assign p_Val2_32_1_fu_992_p0 = p_Val2_14_reg_3237;

assign p_Val2_32_1_fu_992_p1 = r_V_1_1_fu_978_p3;

assign p_Val2_32_1_fu_992_p2 = ($signed(p_Val2_32_1_fu_992_p0) * $signed(p_Val2_32_1_fu_992_p1));

assign p_Val2_32_2_fu_1149_p0 = p_Val2_36_1_reg_3284;

assign p_Val2_32_2_fu_1149_p1 = r_V_1_2_fu_1135_p3;

assign p_Val2_32_2_fu_1149_p2 = ($signed(p_Val2_32_2_fu_1149_p0) * $signed(p_Val2_32_2_fu_1149_p1));

assign p_Val2_32_3_fu_1306_p0 = p_Val2_36_2_reg_3331;

assign p_Val2_32_3_fu_1306_p1 = r_V_1_3_fu_1292_p3;

assign p_Val2_32_3_fu_1306_p2 = ($signed(p_Val2_32_3_fu_1306_p0) * $signed(p_Val2_32_3_fu_1306_p1));

assign p_Val2_32_4_fu_1463_p0 = p_Val2_36_3_reg_3378;

assign p_Val2_32_4_fu_1463_p1 = r_V_1_4_fu_1449_p3;

assign p_Val2_32_4_fu_1463_p2 = ($signed(p_Val2_32_4_fu_1463_p0) * $signed(p_Val2_32_4_fu_1463_p1));

assign p_Val2_32_5_fu_1620_p0 = p_Val2_36_4_reg_3425;

assign p_Val2_32_5_fu_1620_p1 = r_V_1_5_fu_1606_p3;

assign p_Val2_32_5_fu_1620_p2 = ($signed(p_Val2_32_5_fu_1620_p0) * $signed(p_Val2_32_5_fu_1620_p1));

assign p_Val2_32_6_fu_1777_p0 = p_Val2_36_5_reg_3472;

assign p_Val2_32_6_fu_1777_p1 = r_V_1_6_fu_1763_p3;

assign p_Val2_32_6_fu_1777_p2 = ($signed(p_Val2_32_6_fu_1777_p0) * $signed(p_Val2_32_6_fu_1777_p1));

assign p_Val2_32_7_fu_2004_p0 = p_Val2_36_6_fu_1870_p2;

assign p_Val2_32_7_fu_2004_p1 = r_V_1_7_fu_1988_p3;

assign p_Val2_32_7_fu_2004_p2 = ($signed(p_Val2_32_7_fu_2004_p0) * $signed(p_Val2_32_7_fu_2004_p1));

assign p_Val2_32_8_fu_2205_p0 = p_Val2_36_7_fu_2041_p2;

assign p_Val2_32_8_fu_2205_p1 = r_V_1_8_fu_2189_p3;

assign p_Val2_32_8_fu_2205_p2 = ($signed(p_Val2_32_8_fu_2205_p0) * $signed(p_Val2_32_8_fu_2205_p1));

assign p_Val2_32_9_fu_2372_p0 = p_Val2_36_8_fu_2242_p2;

assign p_Val2_32_9_fu_2372_p1 = r_V_1_9_fu_2356_p3;

assign p_Val2_32_9_fu_2372_p2 = ($signed(p_Val2_32_9_fu_2372_p0) * $signed(p_Val2_32_9_fu_2372_p1));

assign p_Val2_32_s_fu_2539_p0 = p_Val2_36_9_fu_2409_p2;

assign p_Val2_32_s_fu_2539_p1 = r_V_1_s_fu_2523_p3;

assign p_Val2_32_s_fu_2539_p2 = ($signed(p_Val2_32_s_fu_2539_p0) * $signed(p_Val2_32_s_fu_2539_p1));

assign p_Val2_34_10_fu_2716_p2 = ($signed(tmp_973_10_cast_fu_2712_p1) + $signed(tmp_71_cast_cast_reg_3185));

assign p_Val2_34_11_fu_2883_p2 = ($signed(tmp_973_11_cast_fu_2879_p1) + $signed(tmp_71_cast_cast_reg_3185));

assign p_Val2_34_1_fu_1045_p2 = ($signed(tmp_973_1_cast_fu_1042_p1) + $signed(tmp_71_cast_cast_reg_3185));

assign p_Val2_34_2_fu_1202_p2 = ($signed(tmp_973_2_cast_fu_1199_p1) + $signed(tmp_71_cast_cast_reg_3185));

assign p_Val2_34_3_fu_1359_p2 = ($signed(tmp_973_3_cast_fu_1356_p1) + $signed(tmp_71_cast_cast_reg_3185));

assign p_Val2_34_4_fu_1516_p2 = ($signed(tmp_973_4_cast_fu_1513_p1) + $signed(tmp_71_cast_cast_reg_3185));

assign p_Val2_34_5_fu_1673_p2 = ($signed(tmp_973_5_cast_fu_1670_p1) + $signed(tmp_71_cast_cast_reg_3185));

assign p_Val2_34_6_fu_1852_p2 = ($signed(tmp_973_6_cast_fu_1849_p1) + $signed(tmp_71_cast_cast_reg_3185));

assign p_Val2_34_7_fu_2014_p2 = ($signed(tmp_973_7_cast_fu_2010_p1) + $signed(tmp_71_cast_cast_reg_3185));

assign p_Val2_34_8_fu_2215_p2 = ($signed(tmp_973_8_cast_fu_2211_p1) + $signed(tmp_71_cast_cast_reg_3185));

assign p_Val2_34_9_fu_2382_p2 = ($signed(tmp_973_9_cast_fu_2378_p1) + $signed(tmp_71_cast_cast_reg_3185));

assign p_Val2_34_s_fu_2549_p2 = ($signed(tmp_973_cast_fu_2545_p1) + $signed(tmp_71_cast_cast_reg_3185));

assign p_Val2_35_10_fu_2721_p4 = {{p_Val2_34_10_fu_2716_p2[59:28]}};

assign p_Val2_35_11_fu_2888_p4 = {{p_Val2_34_11_fu_2883_p2[59:28]}};

assign p_Val2_35_1_fu_1050_p4 = {{p_Val2_34_1_fu_1045_p2[59:28]}};

assign p_Val2_35_2_fu_1207_p4 = {{p_Val2_34_2_fu_1202_p2[59:28]}};

assign p_Val2_35_3_fu_1364_p4 = {{p_Val2_34_3_fu_1359_p2[59:28]}};

assign p_Val2_35_4_fu_1521_p4 = {{p_Val2_34_4_fu_1516_p2[59:28]}};

assign p_Val2_35_5_fu_1678_p4 = {{p_Val2_34_5_fu_1673_p2[59:28]}};

assign p_Val2_35_6_fu_1857_p4 = {{p_Val2_34_6_fu_1852_p2[59:28]}};

assign p_Val2_35_7_fu_2019_p4 = {{p_Val2_34_7_fu_2014_p2[59:28]}};

assign p_Val2_35_8_fu_2220_p4 = {{p_Val2_34_8_fu_2215_p2[59:28]}};

assign p_Val2_35_9_fu_2387_p4 = {{p_Val2_34_9_fu_2382_p2[59:28]}};

assign p_Val2_35_s_fu_2554_p4 = {{p_Val2_34_s_fu_2549_p2[59:28]}};

assign p_Val2_36_10_fu_2743_p2 = (tmp_101_10_fu_2739_p1 + p_Val2_35_10_fu_2721_p4);

assign p_Val2_36_11_fu_2910_p2 = (tmp_101_11_fu_2906_p1 + p_Val2_35_11_fu_2888_p4);

assign p_Val2_36_1_fu_1063_p2 = (tmp_101_1_fu_1060_p1 + p_Val2_35_1_fu_1050_p4);

assign p_Val2_36_2_fu_1220_p2 = (tmp_101_2_fu_1217_p1 + p_Val2_35_2_fu_1207_p4);

assign p_Val2_36_3_fu_1377_p2 = (tmp_101_3_fu_1374_p1 + p_Val2_35_3_fu_1364_p4);

assign p_Val2_36_4_fu_1534_p2 = (tmp_101_4_fu_1531_p1 + p_Val2_35_4_fu_1521_p4);

assign p_Val2_36_5_fu_1691_p2 = (tmp_101_5_fu_1688_p1 + p_Val2_35_5_fu_1678_p4);

assign p_Val2_36_6_fu_1870_p2 = (tmp_101_6_fu_1867_p1 + p_Val2_35_6_fu_1857_p4);

assign p_Val2_36_7_fu_2041_p2 = (tmp_101_7_fu_2037_p1 + p_Val2_35_7_fu_2019_p4);

assign p_Val2_36_8_fu_2242_p2 = (tmp_101_8_fu_2238_p1 + p_Val2_35_8_fu_2220_p4);

assign p_Val2_36_9_fu_2409_p2 = (tmp_101_9_fu_2405_p1 + p_Val2_35_9_fu_2387_p4);

assign p_Val2_36_s_fu_2576_p2 = (tmp_101_s_fu_2572_p1 + p_Val2_35_s_fu_2554_p4);

assign p_Val2_37_10_fu_2749_p2 = (p_Val2_28_10_fu_2626_p2 - p_Val2_31_10_fu_2664_p2);

assign p_Val2_37_11_fu_2916_p2 = (p_Val2_28_11_fu_2793_p2 - p_Val2_31_11_fu_2831_p2);

assign p_Val2_37_1_fu_1069_p2 = (p_Val2_28_1_fu_1009_p2 - p_Val2_31_1_fu_1017_p2);

assign p_Val2_37_2_fu_1226_p2 = (p_Val2_28_2_fu_1166_p2 - p_Val2_31_2_fu_1174_p2);

assign p_Val2_37_3_fu_1383_p2 = (p_Val2_28_3_fu_1323_p2 - p_Val2_31_3_fu_1331_p2);

assign p_Val2_37_4_fu_1540_p2 = (p_Val2_28_4_fu_1480_p2 - p_Val2_31_4_fu_1488_p2);

assign p_Val2_37_5_fu_1697_p2 = (p_Val2_28_5_fu_1637_p2 - p_Val2_31_5_fu_1645_p2);

assign p_Val2_37_6_fu_1876_p2 = (p_Val2_28_6_fu_1812_p2 - p_Val2_31_6_fu_1820_p2);

assign p_Val2_37_7_fu_2047_p2 = (p_Val2_28_7_fu_1920_p2 - p_Val2_31_7_fu_1958_p2);

assign p_Val2_37_8_fu_2248_p2 = (p_Val2_28_8_fu_2091_p2 - p_Val2_31_8_fu_2129_p2);

assign p_Val2_37_9_fu_2415_p2 = (p_Val2_28_9_fu_2292_p2 - p_Val2_31_9_fu_2330_p2);

assign p_Val2_37_s_fu_2582_p2 = (p_Val2_28_s_fu_2459_p2 - p_Val2_31_s_fu_2497_p2);

assign p_Val2_39_10_fu_2755_p2 = (z0_re_V_load_reg_129 + p_Val2_37_10_fu_2749_p2);

assign p_Val2_39_11_fu_2922_p2 = (z0_re_V_load_reg_129 + p_Val2_37_11_fu_2916_p2);

assign p_Val2_39_1_fu_1075_p2 = (p_Val2_37_1_fu_1069_p2 + z0_re_V_load_reg_129);

assign p_Val2_39_2_fu_1232_p2 = (p_Val2_37_2_fu_1226_p2 + z0_re_V_load_reg_129);

assign p_Val2_39_3_fu_1389_p2 = (z0_re_V_load_reg_129 + p_Val2_37_3_fu_1383_p2);

assign p_Val2_39_4_fu_1546_p2 = (p_Val2_37_4_fu_1540_p2 + z0_re_V_load_reg_129);

assign p_Val2_39_5_fu_1703_p2 = (p_Val2_37_5_fu_1697_p2 + z0_re_V_load_reg_129);

assign p_Val2_39_6_fu_1882_p2 = (z0_re_V_load_reg_129 + p_Val2_37_6_fu_1876_p2);

assign p_Val2_39_7_fu_2053_p2 = (p_Val2_37_7_fu_2047_p2 + z0_re_V_load_reg_129);

assign p_Val2_39_8_fu_2254_p2 = (z0_re_V_load_reg_129 + p_Val2_37_8_fu_2248_p2);

assign p_Val2_39_9_fu_2421_p2 = (z0_re_V_load_reg_129 + p_Val2_37_9_fu_2415_p2);

assign p_Val2_39_s_fu_2588_p2 = (p_Val2_37_s_fu_2582_p2 + z0_re_V_load_reg_129);

assign p_Val2_3_fu_795_p0 = OP1_V_4_fu_791_p1;

assign p_Val2_3_fu_795_p1 = OP1_V_4_fu_791_p1;

assign p_Val2_3_fu_795_p2 = ($signed(p_Val2_3_fu_795_p0) * $signed(p_Val2_3_fu_795_p1));

assign p_Val2_4_fu_380_p3 = ((tmp_5_fu_338_p2[0:0] === 1'b1) ? tmp_29_fu_369_p1 : p_Val2_0_i_i_i1_fu_373_p3);

assign p_Val2_5_fu_420_p2 = (tmp_14_fu_416_p1 + p_Val2_4_fu_380_p3);

assign p_Val2_7_fu_640_p3 = ((tmp_23_fu_598_p2[0:0] === 1'b1) ? tmp_49_fu_629_p1 : p_Val2_0_i_i_i5_fu_633_p3);

assign p_Val2_8_fu_680_p2 = (tmp_32_fu_676_p1 + p_Val2_7_fu_640_p3);

assign p_Val2_s_8_fu_767_p0 = OP1_V_3_fu_763_p1;

assign p_Val2_s_8_fu_767_p1 = OP1_V_3_fu_763_p1;

assign p_Val2_s_8_fu_767_p2 = ($signed(p_Val2_s_8_fu_767_p0) * $signed(p_Val2_s_8_fu_767_p1));

assign p_Val2_s_fu_231_p1 = grp_fu_227_p1;

assign p_s_fu_467_p3 = ((sel_tmp7_fu_463_p2[0:0] === 1'b1) ? tmp_10_fu_436_p2 : sel_tmp3_fu_456_p3);

assign qb_1_fu_669_p3 = ((tmp_30_fu_648_p2[0:0] === 1'b1) ? isneg_1_reg_3103 : tmp_50_fu_662_p3);

assign qb_fu_409_p3 = ((tmp_12_fu_388_p2[0:0] === 1'b1) ? isneg_reg_3021 : tmp_42_fu_402_p3);

assign r_V_10_fu_2511_p2 = ($signed(tmp_92_s_fu_2503_p1) + $signed(tmp_93_s_fu_2507_p1));

assign r_V_11_fu_2678_p2 = ($signed(tmp_93_10_fu_2674_p1) + $signed(tmp_92_10_fu_2670_p1));

assign r_V_12_fu_2845_p2 = ($signed(tmp_93_11_fu_2841_p1) + $signed(tmp_92_11_fu_2837_p1));

assign r_V_1_10_fu_2690_p3 = {{p_Val2_39_s_fu_2588_p2}, {1'd0}};

assign r_V_1_11_fu_2857_p3 = {{p_Val2_39_10_fu_2755_p2}, {1'd0}};

assign r_V_1_1_fu_978_p3 = {{p_Val2_16_reg_3243}, {1'd0}};

assign r_V_1_2_fu_1135_p3 = {{p_Val2_39_1_reg_3290}, {1'd0}};

assign r_V_1_3_fu_1292_p3 = {{p_Val2_39_2_reg_3337}, {1'd0}};

assign r_V_1_4_fu_1449_p3 = {{p_Val2_39_3_reg_3384}, {1'd0}};

assign r_V_1_5_fu_1606_p3 = {{p_Val2_39_4_reg_3431}, {1'd0}};

assign r_V_1_6_fu_1763_p3 = {{p_Val2_39_5_reg_3478}, {1'd0}};

assign r_V_1_7_fu_1988_p3 = {{p_Val2_39_6_fu_1882_p2}, {1'd0}};

assign r_V_1_8_fu_2189_p3 = {{p_Val2_39_7_fu_2053_p2}, {1'd0}};

assign r_V_1_9_fu_2356_p3 = {{p_Val2_39_8_fu_2254_p2}, {1'd0}};

assign r_V_1_fu_819_p3 = {{ap_phi_mux_p_Val2_39_12_phi_fu_197_p4}, {1'd0}};

assign r_V_1_s_fu_2523_p3 = {{p_Val2_39_9_fu_2421_p2}, {1'd0}};

assign r_V_2_fu_1187_p2 = ($signed(tmp_92_2_fu_1179_p1) + $signed(tmp_93_2_fu_1183_p1));

assign r_V_3_fu_1344_p2 = ($signed(tmp_93_3_fu_1340_p1) + $signed(tmp_92_3_fu_1336_p1));

assign r_V_4_fu_1501_p2 = ($signed(tmp_92_4_fu_1493_p1) + $signed(tmp_93_4_fu_1497_p1));

assign r_V_5_fu_1658_p2 = ($signed(tmp_92_5_fu_1650_p1) + $signed(tmp_93_5_fu_1654_p1));

assign r_V_6_fu_1833_p2 = ($signed(tmp_93_6_fu_1829_p1) + $signed(tmp_92_6_fu_1825_p1));

assign r_V_7_fu_1972_p2 = ($signed(tmp_92_7_fu_1964_p1) + $signed(tmp_93_7_fu_1968_p1));

assign r_V_8_fu_2143_p2 = ($signed(tmp_93_8_fu_2139_p1) + $signed(tmp_92_8_fu_2135_p1));

assign r_V_9_fu_2344_p2 = ($signed(tmp_93_9_fu_2340_p1) + $signed(tmp_92_9_fu_2336_p1));

assign r_V_fu_873_p2 = ($signed(tmp_39_fu_869_p1) + $signed(tmp_38_fu_865_p1));

assign r_V_s_fu_1030_p2 = ($signed(tmp_92_1_fu_1022_p1) + $signed(tmp_93_1_fu_1026_p1));

assign sel_tmp10_fu_686_p2 = (($signed(F2_1_reg_3120) < $signed(12'd28)) ? 1'b1 : 1'b0);

assign sel_tmp11_fu_723_p2 = (sel_tmp10_reg_3176 & icmp5_reg_3164);

assign sel_tmp1_fu_446_p2 = (tmp_3_reg_3068 ^ 1'd1);

assign sel_tmp2_fu_451_p2 = (tmp_9_reg_3046 & sel_tmp1_fu_446_p2);

assign sel_tmp3_fu_456_p3 = ((sel_tmp2_fu_451_p2[0:0] === 1'b1) ? p_Val2_5_reg_3088 : sel_tmp_fu_440_p3);

assign sel_tmp4_fu_700_p3 = ((tmp_22_reg_3150[0:0] === 1'b1) ? tmp_47_reg_3157 : 32'd0);

assign sel_tmp5_fu_706_p2 = (tmp_22_reg_3150 ^ 1'd1);

assign sel_tmp6_fu_426_p2 = (($signed(F2_reg_3038) < $signed(12'd28)) ? 1'b1 : 1'b0);

assign sel_tmp7_fu_463_p2 = (sel_tmp6_reg_3094 & icmp_reg_3082);

assign sel_tmp8_fu_711_p2 = (tmp_19_reg_3128 & sel_tmp5_fu_706_p2);

assign sel_tmp9_fu_716_p3 = ((sel_tmp8_fu_711_p2[0:0] === 1'b1) ? p_Val2_8_reg_3170 : sel_tmp4_fu_700_p3);

assign sel_tmp_fu_440_p3 = ((tmp_3_reg_3068[0:0] === 1'b1) ? tmp_24_reg_3075 : 32'd0);

assign sh_amt_1_cast_fu_586_p1 = $signed(sh_amt_1_fu_581_p3);

assign sh_amt_1_fu_581_p3 = ((tmp_19_reg_3128[0:0] === 1'b1) ? tmp_20_reg_3134 : tmp_21_reg_3140);

assign sh_amt_cast_fu_326_p1 = $signed(sh_amt_fu_321_p3);

assign sh_amt_fu_321_p3 = ((tmp_9_reg_3046[0:0] === 1'b1) ? tmp_s_reg_3052 : tmp_1_reg_3058);

assign tmp10_fu_2985_p2 = (tmp_95_10_cast_fu_2977_p1 + tmp_95_cast_fu_2974_p1);

assign tmp1_fu_2159_p2 = (tmp_95_6_fu_1845_p1 + mandelbrot_float_fl_reg_216);

assign tmp2_fu_2165_p2 = (tmp_95_4_cast_fu_1803_p1 + tmp_95_5_cast_fu_1806_p1);

assign tmp39_cast_fu_2934_p1 = tmp3_reg_3523;

assign tmp3_fu_2171_p2 = (tmp_95_7_cast_fu_1984_p1 + tmp2_fu_2165_p2);

assign tmp41_cast_fu_2961_p1 = tmp8_fu_2955_p2;

assign tmp42_cast_fu_2948_p1 = tmp5_fu_2942_p2;

assign tmp43_cast_fu_2952_p1 = tmp7_reg_3528;

assign tmp47_cast_fu_2991_p1 = tmp10_fu_2985_p2;

assign tmp4_fu_2937_p2 = (tmp1_reg_3518 + tmp39_cast_fu_2934_p1);

assign tmp5_fu_2942_p2 = (tmp_79_cast_fu_2928_p1 + tmp_95_3_cast_fu_2931_p1);

assign tmp6_fu_2177_p2 = (tmp_95_8_cast_fu_2155_p1 + tmp_95_1_cast_fu_1797_p1);

assign tmp7_fu_2183_p2 = (tmp_95_2_cast_fu_1800_p1 + tmp6_fu_2177_p2);

assign tmp8_fu_2955_p2 = (tmp42_cast_fu_2948_p1 + tmp43_cast_fu_2952_p1);

assign tmp9_fu_2980_p2 = (tmp_95_9_fu_2971_p1 + tmp_96_8_reg_3563);

assign tmp_101_10_fu_2739_p1 = tmp_86_fu_2731_p3;

assign tmp_101_11_fu_2906_p1 = tmp_89_fu_2898_p3;

assign tmp_101_1_fu_1060_p1 = tmp_56_reg_3274;

assign tmp_101_2_fu_1217_p1 = tmp_59_reg_3321;

assign tmp_101_3_fu_1374_p1 = tmp_62_reg_3368;

assign tmp_101_4_fu_1531_p1 = tmp_65_reg_3415;

assign tmp_101_5_fu_1688_p1 = tmp_68_reg_3462;

assign tmp_101_6_fu_1867_p1 = tmp_71_reg_3509;

assign tmp_101_7_fu_2037_p1 = tmp_74_fu_2029_p3;

assign tmp_101_8_fu_2238_p1 = tmp_77_fu_2230_p3;

assign tmp_101_9_fu_2405_p1 = tmp_80_fu_2397_p3;

assign tmp_101_s_fu_2572_p1 = tmp_83_fu_2564_p3;

assign tmp_10_fu_436_p2 = tmp_24_reg_3075 << sh_amt_cast_reg_3063;

assign tmp_11_fu_261_p1 = p_Val2_s_fu_231_p1[51:0];

assign tmp_12_fu_388_p2 = (($signed(tmp_s_reg_3052) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign tmp_13_fu_393_p2 = ($signed(12'd4067) + $signed(F2_reg_3038));

assign tmp_14_fu_416_p1 = qb_fu_409_p3;

assign tmp_15_fu_431_p2 = (($signed(F2_reg_3038) > $signed(12'd27)) ? 1'b1 : 1'b0);

assign tmp_15_s_fu_483_p3 = ((icmp_reg_3082[0:0] === 1'b1) ? tmp_10_fu_436_p2 : 32'd0);

assign tmp_16_fu_517_p1 = exp_tmp_V_1_fu_507_p4;

assign tmp_17_cast_fu_398_p1 = $signed(tmp_13_fu_393_p2);

assign tmp_17_fu_525_p3 = {{1'd1}, {tmp_46_fu_521_p1}};

assign tmp_18_fu_551_p2 = ((tmp_44_fu_495_p1 == 63'd0) ? 1'b1 : 1'b0);

assign tmp_19_fu_563_p2 = (($signed(F2_1_fu_557_p2) > $signed(12'd28)) ? 1'b1 : 1'b0);

assign tmp_1_fu_315_p2 = (12'd28 - F2_fu_297_p2);

assign tmp_20_fu_569_p2 = ($signed(12'd4068) + $signed(F2_1_fu_557_p2));

assign tmp_21_fu_575_p2 = (12'd28 - F2_1_fu_557_p2);

assign tmp_22_fu_590_p2 = ((F2_1_reg_3120 == 12'd28) ? 1'b1 : 1'b0);

assign tmp_23_fu_598_p2 = ((sh_amt_1_fu_581_p3 < 12'd54) ? 1'b1 : 1'b0);

assign tmp_24_fu_335_p1 = man_V_4_reg_3027[31:0];

assign tmp_25_fu_620_p1 = $unsigned(sh_amt_1_cast_fu_586_p1);

assign tmp_26_fu_344_p4 = {{sh_amt_fu_321_p3[11:5]}};

assign tmp_27_fu_624_p2 = $signed(man_V_11_reg_3109) >>> tmp_25_fu_620_p1;

assign tmp_28_fu_696_p2 = tmp_47_reg_3157 << sh_amt_1_cast_reg_3145;

assign tmp_29_fu_369_p1 = tmp_6_fu_364_p2[31:0];

assign tmp_2_fu_257_p1 = exp_tmp_V_fu_247_p4;

assign tmp_30_fu_648_p2 = (($signed(tmp_20_reg_3134) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign tmp_31_fu_653_p2 = ($signed(12'd4067) + $signed(F2_1_reg_3120));

assign tmp_32_fu_676_p1 = qb_1_fu_669_p3;

assign tmp_33_fu_691_p2 = (($signed(F2_1_reg_3120) > $signed(12'd27)) ? 1'b1 : 1'b0);

assign tmp_34_fu_751_p3 = {{ap_phi_mux_z0_im_V_load_phi_fu_161_p6}, {28'd0}};

assign tmp_35_fu_849_p1 = tmp_51_reg_3207;

assign tmp_37_fu_857_p1 = tmp_52_reg_3217;

assign tmp_38_fu_865_p1 = $signed(p_Val2_2_fu_852_p2);

assign tmp_39_fu_869_p1 = $signed(p_Val2_10_fu_860_p2);

assign tmp_3_fu_330_p2 = ((F2_reg_3038 == 12'd28) ? 1'b1 : 1'b0);

assign tmp_40_fu_879_p2 = (($signed(r_V_fu_873_p2) < $signed(33'd1073741825)) ? 1'b1 : 1'b0);

assign tmp_41_fu_903_p1 = tmp_53_reg_3227;

assign tmp_42_cast_fu_885_p1 = p_Val2_11_reg_3222;

assign tmp_42_fu_402_p3 = man_V_4_reg_3027[tmp_17_cast_fu_398_p1];

assign tmp_43_mux_fu_737_p3 = ((tmp_22_reg_3150[0:0] === 1'b1) ? tmp_47_reg_3157 : p_Val2_8_reg_3170);

assign tmp_44_fu_495_p1 = p_Val2_21_fu_491_p1[62:0];

assign tmp_46_fu_521_p1 = p_Val2_21_fu_491_p1[51:0];

assign tmp_47_fu_595_p1 = man_V_11_reg_3109[31:0];

assign tmp_48_fu_604_p4 = {{sh_amt_1_fu_581_p3[11:5]}};

assign tmp_49_fu_629_p1 = tmp_27_fu_624_p2[31:0];

assign tmp_4_fu_235_p1 = p_Val2_s_fu_231_p1[62:0];

assign tmp_4_mux_fu_477_p3 = ((tmp_3_reg_3068[0:0] === 1'b1) ? tmp_24_reg_3075 : p_Val2_5_reg_3088);

assign tmp_50_fu_662_p3 = man_V_11_reg_3109[tmp_52_cast_fu_658_p1];

assign tmp_50_s_fu_743_p3 = ((icmp5_reg_3164[0:0] === 1'b1) ? tmp_28_fu_696_p2 : 32'd0);

assign tmp_52_cast_fu_658_p1 = $signed(tmp_31_fu_653_p2);

assign tmp_5_fu_338_p2 = ((sh_amt_fu_321_p3 < 12'd54) ? 1'b1 : 1'b0);

assign tmp_6_fu_364_p2 = $signed(man_V_4_reg_3027) >>> tmp_8_fu_360_p1;

assign tmp_71_cast_cast_fu_759_p1 = $signed(tmp_34_fu_751_p3);

assign tmp_72_fu_1908_p3 = p_Val2_26_7_fu_1892_p2[32'd27];

assign tmp_73_fu_1946_p3 = p_Val2_29_7_fu_1930_p2[32'd27];

assign tmp_74_fu_2029_p3 = p_Val2_32_7_fu_2004_p2[32'd27];

assign tmp_75_fu_2079_p3 = p_Val2_26_8_fu_2063_p2[32'd27];

assign tmp_76_fu_2117_p3 = p_Val2_29_8_fu_2101_p2[32'd27];

assign tmp_77_fu_2230_p3 = p_Val2_32_8_fu_2205_p2[32'd27];

assign tmp_78_fu_2280_p3 = p_Val2_26_9_fu_2264_p2[32'd27];

assign tmp_79_cast_fu_2928_p1 = tmp_40_reg_3232;

assign tmp_79_fu_2318_p3 = p_Val2_29_9_fu_2302_p2[32'd27];

assign tmp_7_fu_291_p2 = ((tmp_4_fu_235_p1 == 63'd0) ? 1'b1 : 1'b0);

assign tmp_80_fu_2397_p3 = p_Val2_32_9_fu_2372_p2[32'd27];

assign tmp_81_fu_2447_p3 = p_Val2_26_s_fu_2431_p2[32'd27];

assign tmp_82_fu_2485_p3 = p_Val2_29_s_fu_2469_p2[32'd27];

assign tmp_83_fu_2564_p3 = p_Val2_32_s_fu_2539_p2[32'd27];

assign tmp_84_fu_2614_p3 = p_Val2_26_10_fu_2598_p2[32'd27];

assign tmp_85_10_fu_2622_p1 = tmp_84_fu_2614_p3;

assign tmp_85_11_fu_2789_p1 = tmp_87_fu_2781_p3;

assign tmp_85_1_fu_1006_p1 = tmp_54_reg_3254;

assign tmp_85_2_fu_1163_p1 = tmp_57_reg_3301;

assign tmp_85_3_fu_1320_p1 = tmp_60_reg_3348;

assign tmp_85_4_fu_1477_p1 = tmp_63_reg_3395;

assign tmp_85_5_fu_1634_p1 = tmp_66_reg_3442;

assign tmp_85_6_fu_1809_p1 = tmp_69_reg_3489;

assign tmp_85_7_fu_1916_p1 = tmp_72_fu_1908_p3;

assign tmp_85_8_fu_2087_p1 = tmp_75_fu_2079_p3;

assign tmp_85_9_fu_2288_p1 = tmp_78_fu_2280_p3;

assign tmp_85_fu_2652_p3 = p_Val2_29_10_fu_2636_p2[32'd27];

assign tmp_85_s_fu_2455_p1 = tmp_81_fu_2447_p3;

assign tmp_86_fu_2731_p3 = p_Val2_32_10_fu_2706_p2[32'd27];

assign tmp_87_fu_2781_p3 = p_Val2_26_11_fu_2765_p2[32'd27];

assign tmp_88_fu_2819_p3 = p_Val2_29_11_fu_2803_p2[32'd27];

assign tmp_89_10_fu_2660_p1 = tmp_85_fu_2652_p3;

assign tmp_89_11_fu_2827_p1 = tmp_88_fu_2819_p3;

assign tmp_89_1_fu_1014_p1 = tmp_55_reg_3264;

assign tmp_89_2_fu_1171_p1 = tmp_58_reg_3311;

assign tmp_89_3_fu_1328_p1 = tmp_61_reg_3358;

assign tmp_89_4_fu_1485_p1 = tmp_64_reg_3405;

assign tmp_89_5_fu_1642_p1 = tmp_67_reg_3452;

assign tmp_89_6_fu_1817_p1 = tmp_70_reg_3499;

assign tmp_89_7_fu_1954_p1 = tmp_73_fu_1946_p3;

assign tmp_89_8_fu_2125_p1 = tmp_76_fu_2117_p3;

assign tmp_89_9_fu_2326_p1 = tmp_79_fu_2318_p3;

assign tmp_89_fu_2898_p3 = p_Val2_32_11_fu_2873_p2[32'd27];

assign tmp_89_s_fu_2493_p1 = tmp_82_fu_2485_p3;

assign tmp_8_fu_360_p1 = $unsigned(sh_amt_cast_fu_326_p1);

assign tmp_92_10_fu_2670_p1 = $signed(p_Val2_28_10_fu_2626_p2);

assign tmp_92_11_fu_2837_p1 = $signed(p_Val2_28_11_fu_2793_p2);

assign tmp_92_1_fu_1022_p1 = $signed(p_Val2_28_1_fu_1009_p2);

assign tmp_92_2_fu_1179_p1 = $signed(p_Val2_28_2_fu_1166_p2);

assign tmp_92_3_fu_1336_p1 = $signed(p_Val2_28_3_fu_1323_p2);

assign tmp_92_4_fu_1493_p1 = $signed(p_Val2_28_4_fu_1480_p2);

assign tmp_92_5_fu_1650_p1 = $signed(p_Val2_28_5_fu_1637_p2);

assign tmp_92_6_fu_1825_p1 = $signed(p_Val2_28_6_fu_1812_p2);

assign tmp_92_7_fu_1964_p1 = $signed(p_Val2_28_7_fu_1920_p2);

assign tmp_92_8_fu_2135_p1 = $signed(p_Val2_28_8_fu_2091_p2);

assign tmp_92_9_fu_2336_p1 = $signed(p_Val2_28_9_fu_2292_p2);

assign tmp_92_s_fu_2503_p1 = $signed(p_Val2_28_s_fu_2459_p2);

assign tmp_93_10_fu_2674_p1 = $signed(p_Val2_31_10_fu_2664_p2);

assign tmp_93_11_fu_2841_p1 = $signed(p_Val2_31_11_fu_2831_p2);

assign tmp_93_1_fu_1026_p1 = $signed(p_Val2_31_1_fu_1017_p2);

assign tmp_93_2_fu_1183_p1 = $signed(p_Val2_31_2_fu_1174_p2);

assign tmp_93_3_fu_1340_p1 = $signed(p_Val2_31_3_fu_1331_p2);

assign tmp_93_4_fu_1497_p1 = $signed(p_Val2_31_4_fu_1488_p2);

assign tmp_93_5_fu_1654_p1 = $signed(p_Val2_31_5_fu_1645_p2);

assign tmp_93_6_fu_1829_p1 = $signed(p_Val2_31_6_fu_1820_p2);

assign tmp_93_7_fu_1968_p1 = $signed(p_Val2_31_7_fu_1958_p2);

assign tmp_93_8_fu_2139_p1 = $signed(p_Val2_31_8_fu_2129_p2);

assign tmp_93_9_fu_2340_p1 = $signed(p_Val2_31_9_fu_2330_p2);

assign tmp_93_s_fu_2507_p1 = $signed(p_Val2_31_s_fu_2497_p2);

assign tmp_94_10_fu_2684_p2 = (($signed(r_V_11_fu_2678_p2) < $signed(33'd1073741825)) ? 1'b1 : 1'b0);

assign tmp_94_11_fu_2851_p2 = (($signed(r_V_12_fu_2845_p2) < $signed(33'd1073741825)) ? 1'b1 : 1'b0);

assign tmp_94_1_fu_1036_p2 = (($signed(r_V_s_fu_1030_p2) < $signed(33'd1073741825)) ? 1'b1 : 1'b0);

assign tmp_94_2_fu_1193_p2 = (($signed(r_V_2_fu_1187_p2) < $signed(33'd1073741825)) ? 1'b1 : 1'b0);

assign tmp_94_3_fu_1350_p2 = (($signed(r_V_3_fu_1344_p2) < $signed(33'd1073741825)) ? 1'b1 : 1'b0);

assign tmp_94_4_fu_1507_p2 = (($signed(r_V_4_fu_1501_p2) < $signed(33'd1073741825)) ? 1'b1 : 1'b0);

assign tmp_94_5_fu_1664_p2 = (($signed(r_V_5_fu_1658_p2) < $signed(33'd1073741825)) ? 1'b1 : 1'b0);

assign tmp_94_6_fu_1839_p2 = (($signed(r_V_6_fu_1833_p2) < $signed(33'd1073741825)) ? 1'b1 : 1'b0);

assign tmp_94_7_fu_1978_p2 = (($signed(r_V_7_fu_1972_p2) < $signed(33'd1073741825)) ? 1'b1 : 1'b0);

assign tmp_94_8_fu_2149_p2 = (($signed(r_V_8_fu_2143_p2) < $signed(33'd1073741825)) ? 1'b1 : 1'b0);

assign tmp_94_9_fu_2350_p2 = (($signed(r_V_9_fu_2344_p2) < $signed(33'd1073741825)) ? 1'b1 : 1'b0);

assign tmp_94_s_fu_2517_p2 = (($signed(r_V_10_fu_2511_p2) < $signed(33'd1073741825)) ? 1'b1 : 1'b0);

assign tmp_95_10_cast_fu_2977_p1 = tmp_94_10_reg_3543;

assign tmp_95_1_cast_fu_1797_p1 = tmp_94_1_reg_3279;

assign tmp_95_2_cast_fu_1800_p1 = tmp_94_2_reg_3326;

assign tmp_95_3_cast_fu_2931_p1 = tmp_94_3_reg_3373;

assign tmp_95_4_cast_fu_1803_p1 = tmp_94_4_reg_3420;

assign tmp_95_5_cast_fu_1806_p1 = tmp_94_5_reg_3467;

assign tmp_95_6_fu_1845_p1 = tmp_94_6_fu_1839_p2;

assign tmp_95_7_cast_fu_1984_p1 = tmp_94_7_fu_1978_p2;

assign tmp_95_8_cast_fu_2155_p1 = tmp_94_8_fu_2149_p2;

assign tmp_95_9_fu_2971_p1 = tmp_94_9_reg_3533;

assign tmp_95_cast_fu_2974_p1 = tmp_94_s_reg_3538;

assign tmp_95_s_fu_3001_p1 = tmp_94_11_reg_3548;

assign tmp_96_1_fu_3004_p2 = (tmp_95_s_fu_3001_p1 + tmp_96_s_fu_2995_p2);

assign tmp_96_8_fu_2965_p2 = (tmp4_fu_2937_p2 + tmp41_cast_fu_2961_p1);

assign tmp_96_s_fu_2995_p2 = (tmp9_fu_2980_p2 + tmp47_cast_fu_2991_p1);

assign tmp_973_10_cast_fu_2712_p1 = p_Val2_32_10_fu_2706_p2;

assign tmp_973_11_cast_fu_2879_p1 = p_Val2_32_11_fu_2873_p2;

assign tmp_973_1_cast_fu_1042_p1 = p_Val2_32_1_reg_3269;

assign tmp_973_2_cast_fu_1199_p1 = p_Val2_32_2_reg_3316;

assign tmp_973_3_cast_fu_1356_p1 = p_Val2_32_3_reg_3363;

assign tmp_973_4_cast_fu_1513_p1 = p_Val2_32_4_reg_3410;

assign tmp_973_5_cast_fu_1670_p1 = p_Val2_32_5_reg_3457;

assign tmp_973_6_cast_fu_1849_p1 = p_Val2_32_6_reg_3504;

assign tmp_973_7_cast_fu_2010_p1 = p_Val2_32_7_fu_2004_p2;

assign tmp_973_8_cast_fu_2211_p1 = p_Val2_32_8_fu_2205_p2;

assign tmp_973_9_cast_fu_2378_p1 = p_Val2_32_9_fu_2372_p2;

assign tmp_973_cast_fu_2545_p1 = p_Val2_32_s_fu_2539_p2;

assign tmp_9_fu_303_p2 = (($signed(F2_fu_297_p2) > $signed(12'd28)) ? 1'b1 : 1'b0);

assign tmp_fu_265_p3 = {{1'd1}, {tmp_11_fu_261_p1}};

assign tmp_s_fu_309_p2 = ($signed(12'd4068) + $signed(F2_fu_297_p2));

always @ (posedge ap_clk) begin
    tmp_71_cast_cast_reg_3185[27:0] <= 28'b0000000000000000000000000000;
    p_Val2_11_reg_3222[0] <= 1'b0;
    p_Val2_32_1_reg_3269[0] <= 1'b0;
    p_Val2_32_2_reg_3316[0] <= 1'b0;
    p_Val2_32_3_reg_3363[0] <= 1'b0;
    p_Val2_32_4_reg_3410[0] <= 1'b0;
    p_Val2_32_5_reg_3457[0] <= 1'b0;
    p_Val2_32_6_reg_3504[0] <= 1'b0;
end

endmodule //mandelbrot
