-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity strm_words2bytes is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    bytes_out_V_TDATA : OUT STD_LOGIC_VECTOR (7 downto 0);
    bytes_out_V_TVALID : OUT STD_LOGIC;
    bytes_out_V_TREADY : IN STD_LOGIC;
    words_in_V_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    words_in_V_empty_n : IN STD_LOGIC;
    words_in_V_read : OUT STD_LOGIC;
    bytes_out_len_loc_dout : IN STD_LOGIC_VECTOR (13 downto 0);
    bytes_out_len_loc_empty_n : IN STD_LOGIC;
    bytes_out_len_loc_read : OUT STD_LOGIC );
end;


architecture behav of strm_words2bytes is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal bytes_out_V_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln144_fu_136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal words_in_V_blk_n : STD_LOGIC;
    signal icmp_ln146_fu_147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal bytes_out_len_loc_blk_n : STD_LOGIC;
    signal bytes_out_len_loc_re_reg_179 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal i_fu_141_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal i_reg_187 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_predicate_op23_read_state2 : BOOLEAN;
    signal regslice_both_bytes_out_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal i_0_i_i_reg_103 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_phi_mux_p_0_1_i_i_phi_fu_117_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln144_fu_127_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_0_i_i_fu_80 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln144_fu_132_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal bytes_out_V_TDATA_int : STD_LOGIC_VECTOR (7 downto 0);
    signal bytes_out_V_TVALID_int : STD_LOGIC;
    signal bytes_out_V_TREADY_int : STD_LOGIC;
    signal regslice_both_bytes_out_V_U_vld_out : STD_LOGIC;

    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_bytes_out_V_U : component regslice_both
    generic map (
        DataWidth => 8)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => bytes_out_V_TDATA_int,
        vld_in => bytes_out_V_TVALID_int,
        ack_in => bytes_out_V_TREADY_int,
        data_out => bytes_out_V_TDATA,
        vld_out => regslice_both_bytes_out_V_U_vld_out,
        ack_out => bytes_out_V_TREADY,
        apdone_blk => regslice_both_bytes_out_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_const_boolean_1 = ap_block_state2_io) or (regslice_both_bytes_out_V_U_apdone_blk = ap_const_logic_1) or ((words_in_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state2 = ap_const_boolean_1)))) and (icmp_ln144_fu_136_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_0_i_i_reg_103_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (bytes_out_V_TREADY_int = ap_const_logic_1))) then 
                i_0_i_i_reg_103 <= i_reg_187;
            elsif ((not(((ap_start = ap_const_logic_0) or (bytes_out_len_loc_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_i_i_reg_103 <= ap_const_lv14_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start = ap_const_logic_0) or (bytes_out_len_loc_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                bytes_out_len_loc_re_reg_179 <= bytes_out_len_loc_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (regslice_both_bytes_out_V_U_apdone_blk = ap_const_logic_1) or ((words_in_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state2 = ap_const_boolean_1)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                i_reg_187 <= i_fu_141_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (regslice_both_bytes_out_V_U_apdone_blk = ap_const_logic_1) or ((words_in_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state2 = ap_const_boolean_1)))) and (icmp_ln144_fu_136_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                p_0_0_i_i_fu_80 <= ap_phi_mux_p_0_1_i_i_phi_fu_117_p4(31 downto 8);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, words_in_V_empty_n, bytes_out_len_loc_empty_n, ap_CS_fsm_state2, icmp_ln144_fu_136_p2, ap_CS_fsm_state3, ap_predicate_op23_read_state2, regslice_both_bytes_out_V_U_apdone_blk, ap_block_state2_io, bytes_out_V_TREADY_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (bytes_out_len_loc_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (regslice_both_bytes_out_V_U_apdone_blk = ap_const_logic_1) or ((words_in_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state2 = ap_const_boolean_1)))) and (icmp_ln144_fu_136_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not(((ap_const_boolean_1 = ap_block_state2_io) or (regslice_both_bytes_out_V_U_apdone_blk = ap_const_logic_1) or ((words_in_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state2 = ap_const_boolean_1)))) and (icmp_ln144_fu_136_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (bytes_out_V_TREADY_int = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, bytes_out_len_loc_empty_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (bytes_out_len_loc_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(words_in_V_empty_n, ap_predicate_op23_read_state2, regslice_both_bytes_out_V_U_apdone_blk)
    begin
                ap_block_state2 <= ((regslice_both_bytes_out_V_U_apdone_blk = ap_const_logic_1) or ((words_in_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state2 = ap_const_boolean_1)));
    end process;


    ap_block_state2_io_assign_proc : process(icmp_ln144_fu_136_p2, bytes_out_V_TREADY_int)
    begin
                ap_block_state2_io <= ((icmp_ln144_fu_136_p2 = ap_const_lv1_0) and (bytes_out_V_TREADY_int = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, words_in_V_empty_n, ap_CS_fsm_state2, icmp_ln144_fu_136_p2, ap_predicate_op23_read_state2, regslice_both_bytes_out_V_U_apdone_blk, ap_block_state2_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (regslice_both_bytes_out_V_U_apdone_blk = ap_const_logic_1) or ((words_in_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state2 = ap_const_boolean_1)))) and (icmp_ln144_fu_136_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_p_0_1_i_i_phi_fu_117_p4_assign_proc : process(words_in_V_dout, ap_CS_fsm_state2, icmp_ln144_fu_136_p2, icmp_ln146_fu_147_p2, zext_ln144_fu_127_p1)
    begin
        if (((icmp_ln144_fu_136_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
            if ((icmp_ln146_fu_147_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_p_0_1_i_i_phi_fu_117_p4 <= zext_ln144_fu_127_p1;
            elsif ((icmp_ln146_fu_147_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_p_0_1_i_i_phi_fu_117_p4 <= words_in_V_dout;
            else 
                ap_phi_mux_p_0_1_i_i_phi_fu_117_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            ap_phi_mux_p_0_1_i_i_phi_fu_117_p4 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_predicate_op23_read_state2_assign_proc : process(icmp_ln144_fu_136_p2, icmp_ln146_fu_147_p2)
    begin
                ap_predicate_op23_read_state2 <= ((icmp_ln146_fu_147_p2 = ap_const_lv1_1) and (icmp_ln144_fu_136_p2 = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(words_in_V_empty_n, ap_CS_fsm_state2, icmp_ln144_fu_136_p2, ap_predicate_op23_read_state2, regslice_both_bytes_out_V_U_apdone_blk, ap_block_state2_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (regslice_both_bytes_out_V_U_apdone_blk = ap_const_logic_1) or ((words_in_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state2 = ap_const_boolean_1)))) and (icmp_ln144_fu_136_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    bytes_out_V_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state2, icmp_ln144_fu_136_p2, ap_CS_fsm_state3, bytes_out_V_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln144_fu_136_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            bytes_out_V_TDATA_blk_n <= bytes_out_V_TREADY_int;
        else 
            bytes_out_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bytes_out_V_TDATA_int <= ap_phi_mux_p_0_1_i_i_phi_fu_117_p4(8 - 1 downto 0);
    bytes_out_V_TVALID <= regslice_both_bytes_out_V_U_vld_out;

    bytes_out_V_TVALID_int_assign_proc : process(words_in_V_empty_n, ap_CS_fsm_state2, icmp_ln144_fu_136_p2, ap_predicate_op23_read_state2, regslice_both_bytes_out_V_U_apdone_blk, ap_block_state2_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (regslice_both_bytes_out_V_U_apdone_blk = ap_const_logic_1) or ((words_in_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state2 = ap_const_boolean_1)))) and (icmp_ln144_fu_136_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            bytes_out_V_TVALID_int <= ap_const_logic_1;
        else 
            bytes_out_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    bytes_out_len_loc_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, bytes_out_len_loc_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bytes_out_len_loc_blk_n <= bytes_out_len_loc_empty_n;
        else 
            bytes_out_len_loc_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bytes_out_len_loc_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, bytes_out_len_loc_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (bytes_out_len_loc_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            bytes_out_len_loc_read <= ap_const_logic_1;
        else 
            bytes_out_len_loc_read <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_141_p2 <= std_logic_vector(unsigned(ap_const_lv14_1) + unsigned(i_0_i_i_reg_103));
    icmp_ln144_fu_136_p2 <= "1" when (i_0_i_i_reg_103 = bytes_out_len_loc_re_reg_179) else "0";
    icmp_ln146_fu_147_p2 <= "1" when (trunc_ln144_fu_132_p1 = ap_const_lv2_0) else "0";
    trunc_ln144_fu_132_p1 <= i_0_i_i_reg_103(2 - 1 downto 0);

    words_in_V_blk_n_assign_proc : process(words_in_V_empty_n, ap_CS_fsm_state2, icmp_ln144_fu_136_p2, icmp_ln146_fu_147_p2)
    begin
        if (((icmp_ln146_fu_147_p2 = ap_const_lv1_1) and (icmp_ln144_fu_136_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            words_in_V_blk_n <= words_in_V_empty_n;
        else 
            words_in_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    words_in_V_read_assign_proc : process(words_in_V_empty_n, ap_CS_fsm_state2, ap_predicate_op23_read_state2, regslice_both_bytes_out_V_U_apdone_blk, ap_block_state2_io)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (regslice_both_bytes_out_V_U_apdone_blk = ap_const_logic_1) or ((words_in_V_empty_n = ap_const_logic_0) and (ap_predicate_op23_read_state2 = ap_const_boolean_1)))) and (ap_predicate_op23_read_state2 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            words_in_V_read <= ap_const_logic_1;
        else 
            words_in_V_read <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln144_fu_127_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_0_0_i_i_fu_80),32));
end behav;
