// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module strm_bytes2words (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        words_out_V_din,
        words_out_V_full_n,
        words_out_V_write,
        bytes_in_V_TDATA,
        bytes_in_V_TVALID,
        bytes_in_V_TREADY,
        bytestrm_len_dout,
        bytestrm_len_empty_n,
        bytestrm_len_read
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [31:0] words_out_V_din;
input   words_out_V_full_n;
output   words_out_V_write;
input  [7:0] bytes_in_V_TDATA;
input   bytes_in_V_TVALID;
output   bytes_in_V_TREADY;
input  [15:0] bytestrm_len_dout;
input   bytestrm_len_empty_n;
output   bytestrm_len_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg words_out_V_write;
reg bytes_in_V_TREADY;
reg bytestrm_len_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    words_out_V_blk_n;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln117_fu_131_p2;
wire   [0:0] icmp_ln126_fu_151_p2;
reg    bytes_in_V_TDATA_blk_n;
reg    bytestrm_len_blk_n;
reg   [15:0] bytestrm_len_read_reg_175;
reg    ap_block_state1;
wire   [15:0] i_fu_136_p2;
reg    ap_predicate_op22_write_state2;
reg    ap_block_state2;
wire   [23:0] trunc_ln117_1_fu_167_p3;
reg   [23:0] r_V_reg_105;
reg   [15:0] i_0_i_reg_116;
wire   [1:0] trunc_ln117_fu_127_p1;
wire   [15:0] tmp_5_fu_157_p4;
reg   [1:0] ap_NS_fsm;
wire    regslice_both_bytes_in_V_U_apdone_blk;
wire   [7:0] bytes_in_V_TDATA_int;
wire    bytes_in_V_TVALID_int;
reg    bytes_in_V_TREADY_int;
wire    regslice_both_bytes_in_V_U_ack_in;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

regslice_both #(
    .DataWidth( 8 ))
regslice_both_bytes_in_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(bytes_in_V_TDATA),
    .vld_in(bytes_in_V_TVALID),
    .ack_in(regslice_both_bytes_in_V_U_ack_in),
    .data_out(bytes_in_V_TDATA_int),
    .vld_out(bytes_in_V_TVALID_int),
    .ack_out(bytes_in_V_TREADY_int),
    .apdone_blk(regslice_both_bytes_in_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~(((words_out_V_full_n == 1'b0) & (ap_predicate_op22_write_state2 == 1'b1)) | ((icmp_ln117_fu_131_p2 == 1'd0) & (bytes_in_V_TVALID_int == 1'b0))) & (icmp_ln117_fu_131_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~(((words_out_V_full_n == 1'b0) & (ap_predicate_op22_write_state2 == 1'b1)) | ((icmp_ln117_fu_131_p2 == 1'd0) & (bytes_in_V_TVALID_int == 1'b0))) & (icmp_ln117_fu_131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_0_i_reg_116 <= i_fu_136_p2;
    end else if ((~((ap_start == 1'b0) | (bytestrm_len_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_i_reg_116 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((words_out_V_full_n == 1'b0) & (ap_predicate_op22_write_state2 == 1'b1)) | ((icmp_ln117_fu_131_p2 == 1'd0) & (bytes_in_V_TVALID_int == 1'b0))) & (icmp_ln117_fu_131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        r_V_reg_105 <= trunc_ln117_1_fu_167_p3;
    end else if ((~((ap_start == 1'b0) | (bytestrm_len_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        r_V_reg_105 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (bytestrm_len_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bytestrm_len_read_reg_175 <= bytestrm_len_dout;
    end
end

always @ (*) begin
    if ((~(((words_out_V_full_n == 1'b0) & (ap_predicate_op22_write_state2 == 1'b1)) | ((icmp_ln117_fu_131_p2 == 1'd0) & (bytes_in_V_TVALID_int == 1'b0))) & (icmp_ln117_fu_131_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~(((words_out_V_full_n == 1'b0) & (ap_predicate_op22_write_state2 == 1'b1)) | ((icmp_ln117_fu_131_p2 == 1'd0) & (bytes_in_V_TVALID_int == 1'b0))) & (icmp_ln117_fu_131_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln117_fu_131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        bytes_in_V_TDATA_blk_n = bytes_in_V_TVALID_int;
    end else begin
        bytes_in_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((bytes_in_V_TVALID == 1'b1) & (regslice_both_bytes_in_V_U_ack_in == 1'b1))) begin
        bytes_in_V_TREADY = 1'b1;
    end else begin
        bytes_in_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~(((words_out_V_full_n == 1'b0) & (ap_predicate_op22_write_state2 == 1'b1)) | ((icmp_ln117_fu_131_p2 == 1'd0) & (bytes_in_V_TVALID_int == 1'b0))) & (icmp_ln117_fu_131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        bytes_in_V_TREADY_int = 1'b1;
    end else begin
        bytes_in_V_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bytestrm_len_blk_n = bytestrm_len_empty_n;
    end else begin
        bytestrm_len_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (bytestrm_len_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        bytestrm_len_read = 1'b1;
    end else begin
        bytestrm_len_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln126_fu_151_p2 == 1'd1) & (icmp_ln117_fu_131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        words_out_V_blk_n = words_out_V_full_n;
    end else begin
        words_out_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((words_out_V_full_n == 1'b0) & (ap_predicate_op22_write_state2 == 1'b1)) | ((icmp_ln117_fu_131_p2 == 1'd0) & (bytes_in_V_TVALID_int == 1'b0))) & (1'b1 == ap_CS_fsm_state2) & (ap_predicate_op22_write_state2 == 1'b1))) begin
        words_out_V_write = 1'b1;
    end else begin
        words_out_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (bytestrm_len_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~(((words_out_V_full_n == 1'b0) & (ap_predicate_op22_write_state2 == 1'b1)) | ((icmp_ln117_fu_131_p2 == 1'd0) & (bytes_in_V_TVALID_int == 1'b0))) & (icmp_ln117_fu_131_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if ((~(((words_out_V_full_n == 1'b0) & (ap_predicate_op22_write_state2 == 1'b1)) | ((icmp_ln117_fu_131_p2 == 1'd0) & (bytes_in_V_TVALID_int == 1'b0))) & (icmp_ln117_fu_131_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (bytestrm_len_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2 = (((words_out_V_full_n == 1'b0) & (ap_predicate_op22_write_state2 == 1'b1)) | ((icmp_ln117_fu_131_p2 == 1'd0) & (bytes_in_V_TVALID_int == 1'b0)));
end

always @ (*) begin
    ap_predicate_op22_write_state2 = ((icmp_ln126_fu_151_p2 == 1'd1) & (icmp_ln117_fu_131_p2 == 1'd0));
end

assign i_fu_136_p2 = (16'd1 + i_0_i_reg_116);

assign icmp_ln117_fu_131_p2 = ((i_0_i_reg_116 == bytestrm_len_read_reg_175) ? 1'b1 : 1'b0);

assign icmp_ln126_fu_151_p2 = ((trunc_ln117_fu_127_p1 == 2'd3) ? 1'b1 : 1'b0);

assign tmp_5_fu_157_p4 = {{r_V_reg_105[23:8]}};

assign trunc_ln117_1_fu_167_p3 = {{bytes_in_V_TDATA_int}, {tmp_5_fu_157_p4}};

assign trunc_ln117_fu_127_p1 = i_0_i_reg_116[1:0];

assign words_out_V_din = {{bytes_in_V_TDATA_int}, {r_V_reg_105}};

endmodule //strm_bytes2words
