# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/trevor/dev/myelect/vivado_video/XVES_0004/proj_4/proj_4.srcs/sources_1/bd/TPG_sim_bd/ip/TPG_sim_bd_v_tpg_0_0/TPG_sim_bd_v_tpg_0_0.xci
# IP: The module: 'TPG_sim_bd_v_tpg_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/trevor/dev/myelect/vivado_video/XVES_0004/proj_4/proj_4.srcs/sources_1/bd/TPG_sim_bd/ip/TPG_sim_bd_v_tpg_0_0/TPG_sim_bd_v_tpg_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TPG_sim_bd_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/trevor/dev/myelect/vivado_video/XVES_0004/proj_4/proj_4.srcs/sources_1/bd/TPG_sim_bd/ip/TPG_sim_bd_v_tpg_0_0/TPG_sim_bd_v_tpg_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TPG_sim_bd_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/trevor/dev/myelect/vivado_video/XVES_0004/proj_4/proj_4.srcs/sources_1/bd/TPG_sim_bd/ip/TPG_sim_bd_v_tpg_0_0/TPG_sim_bd_v_tpg_0_0.xci
# IP: The module: 'TPG_sim_bd_v_tpg_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/trevor/dev/myelect/vivado_video/XVES_0004/proj_4/proj_4.srcs/sources_1/bd/TPG_sim_bd/ip/TPG_sim_bd_v_tpg_0_0/TPG_sim_bd_v_tpg_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TPG_sim_bd_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/trevor/dev/myelect/vivado_video/XVES_0004/proj_4/proj_4.srcs/sources_1/bd/TPG_sim_bd/ip/TPG_sim_bd_v_tpg_0_0/TPG_sim_bd_v_tpg_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TPG_sim_bd_v_tpg_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
